### ISSUE TITLE
Focus stack

### ISSUE THREAD

**Issue by Pascal1965** [ottokiksmaler/nx500_nx1_modding#10]
Hi everybody!
I'm trying to use focus stack. I have green dots on the left off the sreen but when I press "EV+AEL" green dots don't desepear and I can't activate focus stack.

**Comment by gitvasile** [comment]
your script has a problem and does not get to the point where dfmsd is killed.
Suggest you redo it, precisely following Otto's instructions.

**Comment by Pascal1965** [comment]
I found instructions on Youtube:
"Go to the GitHub link and download the sd.zip, extract it to a SD Card.
The info.tg file should be in the root of the SD card, the rest in the scripts directory.
download keyscan, focus_buttons and focus_stack from GitHub and put them in the scripts directory
In the scripts directory, create a file for the key combination you require, so if you want to use EV+AEL to execute the focus button program, create a file called EV_AEL.sh (or edit if there is already an existing one), open the file in a text editor and put in the path to the executable, so for focus stack you would have"
Is it the correct way?

**Comment by Pascal1965** [comment]
Nobody can tell me where are the intructions for focus stack?

**Comment by ottokiksmaler** [comment]
Sorry, I'll be at computer in one hour.

**Comment by ottokiksmaler** [comment]
Yes, unpack sd.zip file to your SD card root, put focus_stack file in scripts folder on SD card and create/edit file named EV_AEL.sh (so SD/scripts/EV_AEL.sh) to contain:
/mnt/mmc/scripts/focus_stack

That's it, when you turn on your camera, wait for green dots to disappear and press EV, click AEL, release EV. It should start focus stacking tool.

**Comment by ottokiksmaler** [comment]
Help from the front page of this repo:

Focus on near point - press "Near"
Focus on far point - press "Far"
Click "Stack" and wait for it to finish
Files are in the usual place - remember to fix exposure/awb/etc as you normally would
Precompiled binary is here: https://github.com/ottokiksmaler/nx500/blob/master/focus_stack

**Comment by Pascal1965** [comment]
I tried it and it works perfectly now!! Thank you Otto!
