### ISSUE TITLE
Binaries no longer on Samsung website

### ISSUE THREAD

**Issue by wanderingstan** [ottokiksmaler/nx500_nx1_modding#102]
Just noticed that the download link reference on the [telnet page](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/2fd15cada1566d23289884aae7557c888b193cb9/Running-telnet-server-on-camera.md) (and maybe others) no longer works:

http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=nx300

Also, manually searching for `nx300` or `nx2000` or `nx500` no longer return any results:
http://opensource.samsung.com/reception.do

If Samsung is no longer hosting this file, is it available elsewhere? If so, we should update the links.

**Comment by ottokiksmaler** [comment]
NX1 seems to be there, as well as NX3000 but other NX cameras are gone. I have NX500 archive but I'm not sure (I'll have to check, if it's all open source it should be ok) if we can legally host it somewhere else.

**Comment by wanderingstan** [comment]
I might also be able to provide hosting and/or bittorrent seed. 

The software seems to be under a [GPL license](https://www.gnu.org/licenses/gpl-3.0.en.html
), which by my reading gives us clear permission to host, i.e. "convey verbatim copies":

> 4. Conveying Verbatim Copies.
> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.

**Comment by ottokiksmaler** [comment]
I went to Samsung site be read everything there and nothing mentions any restrictions related to hosting or further distribution, relegating everything to licenses in the archive.
Maybe we should just do what Samsung did and host them with click through disclaimer?

**Comment by wanderingstan** [comment]
I'm not a lawyer, but their click through disclaimer appears to be an extra layer of protection from them getting sued when people use the software and somehow break their camera. I don't think such a warning is absolutely needed when hosted elsewhere, as it's already covered in the GPL in section 16, even in ALL CAPS:

> 16. Limitation of Liability.
> IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
