### ISSUE TITLE
Removing hack

### ISSUE THREAD

**Issue by HerbM3** [ottokiksmaler/nx500_nx1_modding#105]
I am selling my NX1. How do I remove the hack?

Thank you.

**Comment by HerbM3** [comment]
Thanks for the quick reply. I’ve been out of this for a while. So I should download the  NX1 firmware from Samsung and run it...? Cool. Thanks!

**Comment by HerbM3** [comment]
I’m on a Mac OS X 10.13 having no luck with iLauncher website. It says my camera is not connected. Any alternatives?

**Comment by HerbM3** [comment]
Sorry to be a headache.

**Comment by ottokiksmaler** [comment]
Download and unzip to, preferably freshly formatted, SD card from here
https://www.samsung.com/us/support/owners/product.devicetype-mobile/galaxy-nx1-camera-nx1-series/

**Comment by HerbM3** [comment]
Thanks! Doing now.
