### ISSUE TITLE
Live Composite mode like by Olympus?

### ISSUE THREAD

**Issue by medienmg** [ottokiksmaler/nx500_nx1_modding#106]
Dear Ottokiksmaler,

have to apologize for my English. 
But I like to ask if it's possible to make an live composite mod like by Olympus Omd Em5 (m2)?

Best regards, Mike

**Comment by ottokiksmaler** [comment]
Hi,

Your English is good, don't worry :) 

Unfortunately, we were not able to make something similar to live composite :(
It seems to work by taking and adding individual frames and that does not work properly on Samsung NX. The only workaround I use is to take a burst of photos (or timelapse if the duration is longer) and then combine them on the computer.
