### ISSUE TITLE
Setting exposure compensation to negative via st command

### ISSUE THREAD

**Issue by woroko** [ottokiksmaler/nx500_nx1_modding#108]
Hi,

This seems like a good place to ask:

Is it possible to set the exposure compensation value (EVC) to a **negative** value via "st cap capdtm setvar EVC 0xHEXVAL 4" or a similar command? If so, could you advice me on the correct syntax for this?

The reason I am asking is that I want to develop an exposure bracketing script for the Samsung Gear 360 (2017) camera. I have already tested that the above st command works for positive values of EVC. I can see that the Android app for Gear 360 is able to set the EVC to negative values (0xFFE2000A or  -1966070), but the st command does not allow this, whether in hex or decimal format.

**Comment by ottokiksmaler** [comment]
OK, I have tested and I here is what I have
`st cap capdtm setvar EVC 0x04ff60000 4`
will set it to -1
`st cap capdtm setvar EVC 0x04ff40000 4`
will set it to -13/10
`st cap capdtm setvar EVC 0x04ff00000 4`
-8/5
`st cap capdtm setvar EVC 0x04feb0000 4`
-2
`st cap capdtm setvar EVC 0x04fe10000 4`
-3
`st cap capdtm setvar EVC 0x04fd70000 4`
-4
`st cap capdtm setvar EVC 0x04fcd0000 4`
And so on (you can see the progression if you need more compensation).

What I do is when I don't want any auto exposure is:
1. Enable M mode
2. Set fixed ISO
3. Set any Shutter Speed

`st key mode m
st cap capdtm setusr 5 0x050001;st cap capdtm setusr 0 4;st cap capdtm setusr 1 0x10004
st cap capdtm setvar TV 64
st key click s2
st cap capdtm setvar TV 128
st key click s2`

TV value is used for shutter speed =1/2^(TV/16) so for TV=128 TV/16=8 => SS=1/2^8=1/250s (it rounds to nearest possible value).

**Comment by woroko** [comment]
Thanks, I was able to get negative EVC working with your instructions.
Manual mode is still not working, maybe it is not implemented on the Gear 360 2017.
