### ISSUE TITLE
patching the zswap instead of RAM.

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#11]
If/when we get a kamikaze camera I would try patching the zswap partition. Can't be THAT difficult.
**which partition is it**? - I have dd'd them and have offline copies that I could work with.

**Comment by ottokiksmaler** [comment]
It's mmcblk0p9 - if you cat it to another file on sd card you will get ~150MB file

**Comment by ottokiksmaler** [comment]
Help from the front page of this repo:

Focus on near point - press "Near"
Focus on far point - press "Far"
Click "Stack" and wait for it to finish
Files are in the usual place - remember to fix exposure/awb/etc as you normally would
Precompiled binary is here: https://github.com/ottokiksmaler/nx500/blob/master/focus_stack
