### ISSUE TITLE
Not able to find IP or get telnet running

### ISSUE THREAD

**Issue by thatoneguy43** [ottokiksmaler/nx500_nx1_modding#110]
Hi, I have followed all the step but when I try to connect via telnet I get an error. telnet: Unable to connect to remote host: Connection refused
I'm trying to connect through windows and it doesn't give me an IP address, but it does give me an IPv4 address. That might be my issue. Where can I find the IP address of the camera?

**Comment by ottokiksmaler** [comment]
Telnet is not started automatically on all mods. Which one did you use?

**Comment by thatoneguy43** [comment]
I was following the "Running telnet server on camera" readme because it looks like you can access a good amount of commands on the camera. What I really want to do with the gear 360 is adjust the shutter speed so that I can take pictures of the night sky. But also lowering the ISO limit to 150 would be nice for pictures in general.

**Comment by ottokiksmaler** [comment]
Ah, gear 360. Ok, when you enter the menu and choose iOS the camera acts as a Wi-Fi access point so you connect to it from the phone or computer (you see the WPA password on the screen of the camera). Then you telnet to whatever the IP is of your gateway (for example, if your IP is 192.168.1.44 you telnet to 192.168.1.1).

I'll also try to make simpler instruction tonight and post it on the gear 360 modding page. I have made a small mod for my gear 360 to lower the ISO to 125 (as low as it goes) so I'll just put it there as well.

**Comment by thatoneguy43** [comment]
Okay I got telnet to work. So what I did was on command prompt used the command ipconfig to check the default gateway and found it was 192.168.43.1 and then did a telnet connection and it worked! That was the main question I had, was how to find the IP address to connect to.

I look forward to seeing the post tonight.

**Comment by thatoneguy43** [comment]
I guess my only question now is: Is there a place with all the commands for the camera? The specific one I am looking for is adjusting the shutter speed.

**Comment by ottokiksmaler** [comment]
Here you go:
https://github.com/ottokiksmaler/gear360_modding/blob/master/README.md

FYI: if you are messing around with exposure, do set the mode to M or S as the default is P and it will ignore anything you set. Also, you should probably experiment with ```st cap capdtm varlist``` and ```st cap capdtm getvar/setvar``` - see here: (https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/ST_CAP_CAPDTM.md)
