### ISSUE TITLE
NX300M related on bitrate hacking

### ISSUE THREAD

**Issue by funtikar** [ottokiksmaler/nx500_nx1_modding#112]
Sorry to bother you, but I was hoping to get a little more information.
I recently knew about the NX300M and bought the NX300M and felt it could use a boost in the bitrate too.

I am not a much experienced programmer or reverse engineer but willing to experiment or even bare the risk of bricking this NX300. 

The hack is patching the di-camera-app and libmmutil_movie.so.0.0.0 am I right?

A few questions too
Are these bitrate patches were already an available option but hidden in official original firmware? but is plainly activated?

or was it introduced and tested to what bitrate and resolution it is able to record?

I guess I would have to dig in with Binwalk and IDA to explore more?

**Comment by ottokiksmaler** [comment]
Sorry, I don't have NX300M. The people who developed bitrate hacks are no longer active here, but they left the documentation on hacks and you should probably read that. It's worth noting that the hacks before and after the latest firmware update are different so I'm not sure how that applies to NX300M. These bitrates are not a part that was just removed or masked, they are parameters sent to encoder so you can input arbitrary numbers there.
