### ISSUE TITLE
Frame rate on HDMI live output

### ISSUE THREAD

**Issue by bortek** [ottokiksmaler/nx500_nx1_modding#113]
I know there has not been much development lately but I wonder about the following in case if you know. HDMI live frame rate is 60 fps on NX500. Is there a way to programmatically set or limit it to 30 or less fps since my hdmi receiving gear has this limitation?

**Comment by ottokiksmaler** [comment]
Sorry, I don't know how to control the HDMI output aside from what's available in the official menus.
