### ISSUE TITLE
Samsung NX500 as a webcam

### ISSUE THREAD

**Issue by qo4on** [ottokiksmaler/nx500_nx1_modding#115]
Hi!
I enabled PTP mode on the NX500 camera and see the green dots on the left side. Windows sees the camera as a disk and allows to copy files. Is it possible to use the camera as a webcam? Unfortunately I don't see it in OBS.

**Comment by Kai-Angne** [comment]
I use the NX500 as a webcam - with HDMI Cable and HDMI to USB Grabber (between 10,- and 20,- Euro). The NX500 delivers a picture while on - not while filming and no Audio (in my case?!) - over HDMI.  Windows recognize it as a video device - works with any webcam/cam software.

**Comment by qo4on** [comment]
I suppose it is possible with USB cable https://youtu.be/-XbNA-FY0ps

**Comment by Kai-Angne** [comment]
As far as i know, it's not possible with the NX500.

**Comment by ottokiksmaler** [comment]
Hi, we were unable to achieve tethered shooting with NX500. NX1 was officially supported by Samsung, but ony via a special SDK.
To use NX500 as a video source you can either use a HDMI capture device (works fine but requires additional hardware) or use it as a streaming input via Wi-Fi but with low resolution and noticeable delay (not really usable).
