### ISSUE TITLE
Options for Galaxy NX (EK-GN120)

### ISSUE THREAD

**Issue by ChasonDeshotel** [ottokiksmaler/nx500_nx1_modding#119]
Is "downgrading" the NX (pre-NX1) to the NX1000 firmware a sure brick or has this just not been looked into? I asked the question a few years ago but I don't remember there being a solid answer. If there's a chance I'm willing to risk it. It's been so many years I don't even remember how the initial hack worked and I'm not keen to do that research again if it's zero chance of success :)

The 360 camera advancements give me a bit of hope

If that doesn't work, what would it take to get the dev tools over? Think we could get lucky with a self-contained binary copy-paste job?

edit: seems that they're on different CPUs :\ so that might be kind of sketchy. 

In that case, would someone mind running a trace on `st app bb tv video` for me?

**Comment by ge0rg** [comment]
The NX brand comes with approximately five different CPU models, and those most probably have very specific hardware configurations for each NX model, resulting in incompatible binaries: https://github.com/ge0rg/samsung-nx-hacks/#device-support

If you manage to flash a firmware file from a different model, chances are that it will be a permanent brick (unless you are good at BGA soldering). If you manage to replace the `di-camera-app` from another model, the camera app will probably crash immediately, but you have a minor chance to restore an original firmware by shorting the double-triangle pad on the mainboard for firmware recovery.

**Comment by ChasonDeshotel** [comment]
Oh hey, thanks for the info! Incoming TED Talk. Since that post, I've spent quite a few hours getting a development environment going and digging around in the Gear 360 code that Samsung open sourced. (this appears to support codenames: nx1, nx360, nx360globe, nx500, and nxmini2)

We could cross-compile that code for the correct processor... but there's large device maps for each unit. GPIO pins, LCD, SPI, I2C, etc.... if someone sourced a schematic with pinouts I would yolo it lol. I have a nicer camera... my only use case with the NX is essentially webcam. From reading the code I know that's possible. There's even a Samsung-written high-speed USB data stream driver, and an open source webcam driver included

The Gear 360 I actually use for taking photos but their software has gotten so bad it's essentially useless so I'm hoping to do the same thing there. Double click and it just dumps an RTMP video feed over WiFi. They're using V4L all over the place we should be able to make that call and intercept the stream.

Now another way to solve the clean HDMI output problem is to just create your own app and push clean output to HDMI. The problem we always had was that none of the apps on the store supported HDMI out... but Samsung in house wrote a DRIMe4 and a DRIMe5 HDMI libraries so they could be super efficient and hit the CPU registers directly... that code, along with the implementation is there for the taking

I don't know how to make an app or I'd do it... right now I'm having to learn how to get all of these compiled pieces (bootloader, kernel, Vimage, etc, etc) into the correct single `.bin` image and hopefully find a way to test without risking the 360 each time

>If you manage to replace the di-camera-app from another model, the camera app will probably crash immediately

Maybe not though. They seem to have done a good job of isolating the functional code from the mapping code. 

And on that note, I thought it would be interesting to load prefman on an older version. It's just sitting there all by itself waiting to cause unexpected fun times on someone's older hardware
