### ISSUE TITLE
program to verify key state?

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#12]
Otto, I have something naughty in mind :-) but before I move on with it, is there a way to check key state - hypothetically, I'd like to be able to do this in a script:
isKeyPressed "OK"
return 0 if yes, 255 if no

**Comment by ottokiksmaler** [comment]
Not from script (but I could probably make it if you define exactly how it should act) but keyscan.c does exactly that in C.

**Comment by gitvasile** [comment]
I just need it to check (without waiting) the state of a key (given in the command line).
Alternatively, it could return the keycode of the key being pressed at the time it is run (this would actually be better).
I do not want it to "consume" the key - just to check whether there's some key currently being depressed.

**Comment by ottokiksmaler** [comment]
Sure, I can adapt keyscan tonight

**Comment by gitvasile** [comment]
"return the keycode" would be best :-)

**Comment by ottokiksmaler** [comment]
Do you want the key code or key name?

**Comment by gitvasile** [comment]
whatever works for you, guess key name would make things a bit more user friendly, but don't worry too much :-)

**Comment by ottokiksmaler** [comment]
Is this OK? https://github.com/ottokiksmaler/nx500_nx1_modding/tree/dev/experiment

**Comment by gitvasile** [comment]
sorry I was digging through the NX500 to see how it boots tonight

The util above would be useful to be able to dynamically skip the sdcard script if the hook was executed with a botton pressed.
I have some ideas on how to force a cold boot and recreate the cold boot hibernation but I am afraid to try :-(

**Comment by ottokiksmaler** [comment]
This will not work at boot time (I mean, it would but would cause serious delay for you). You would have to directly read from /dev/inputX (like in keyscan) or better yet check the position of mode dial or something similar already provided by camera.

**Comment by gitvasile** [comment]
Sorry I meant at thaw (or wake-up) time, I know full boot takes a long time...

**Comment by ottokiksmaler** [comment]
Yes, it will work but only after the keyscan has started.
