### ISSUE TITLE
Does autofocus work well when recording video?

### ISSUE THREAD

**Issue by qo4on** [ottokiksmaler/nx500_nx1_modding#124]
I've noticed that the autofocus is constantly refocusing for no reason while recording video on the NX500 v1.12. This is especially noticeable during the slow transition from near object to far object and back again. This happens even when there is no motion in the frame. Have you ever noticed anything similar and is there any way to fix this?

I found [an example video](https://www.youtube.com/watch?v=4_uZIUluOU8) that shows the problem

**Comment by ge0rg** [comment]
Sorry, but the AF performance in video is not perfect on the NX cameras, and varies strongly with the lenses. The AF FAILED RELEASE ENABLE option is only for shooting still photos when the AF wasn't able to focus, and the camera would show a red square instead.
