### ISSUE TITLE
RTOS <=> Linux communication

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#15]
From what I gathered they actually communicate through shared memory and this is how the st command sends orders to the RTOS.
So in a sense **st** is equivalent to the **di-camera-app** in the sense that they both control the camera.

Or am I missing something?

**Comment by ottokiksmaler** [comment]
It seems st *sometimes* calls di-camera-app (or communicates via it) and sometimes it goes around it and does the communication directly. 
For example, st cap is in /usr/bin/mcbtest, direct access to hdi, gpio, writel, readl, dump, pmu, log, LCD, clk, firmware, leak, devman, stlcd, bat, rtc, tbm, misc, oic, micom, dvfs, adc is in libshell-command.so (but might be offloaded elsewhere), but st app is in di-camera-app (makes sense). And then they use libprefman.so (di-camera-app does) and so on and so on. Some of the sommands do exactly nothing, some exist but are not declared anywhere in st (not part of help files). It's a mess - they are really leftovers from debugging.

**Comment by gitvasile** [comment]
from what I can see the RTOS is actually a T-Kernel and it runs on at least one of the 4 "hidden" cores of the DRIMe.
If only we could find a way to communicate with it - the st app actually sends it commands through some sort of shell.
Also, one of the libs in /usr/lib - cannot remember the name right now but it ends in **fw-prod.so** actually has a main() function - too bad it crashes on launch with segfault.

**Comment by gitvasile** [comment]
Also, I am fairly sure the RTOS is actually loaded from one of the "unknown" partitions. Is there any documentation/too that would allow understanding the way the t-kernel boots?
From what crashlogs I was able to see, it is overflowing with logging information - if you would know how to get to this logs.

**Comment by ottokiksmaler** [comment]
It's TRON OS and it's most likely in following partitions 

rtos /dev/mmcblk0p7 30 rom.bin 2 None raw
rtos_data /dev/mmcblk0p8 50 none 3 None raw

**Comment by ottokiksmaler** [comment]
Also, there is a st command IIRC to reload the rtos but it crashes the camera.

**Comment by gitvasile** [comment]
hmmm. when I get home I will run a strings command on dumps of these two... who konws what I can find...
Also, what is the difference/relationship between TRON and T-Kernel? - because I saw a reference to t-kernel somewhere in the code.

**Comment by gitvasile** [comment]
btw. running telnet off /root will let telnet session to survive di-camera-app crash ;-)

**Comment by ottokiksmaler** [comment]
Not only root, you can put it on /opt/usr/devel/bin for example, I'm running ftpd like that :) 

TRON is the OS that uses t-kernel. But, it's distributed under permissive license so there's no telling what Samsung did to it.

**Comment by ottokiksmaler** [comment]
Beware that anything depending on mmc will be killed as mmc is unmounted every time during suspend / hibernate.

**Comment by gitvasile** [comment]
yep - by the way i moved the binaries I work with (debugger, etc) /opt/usr/devel/bin since it is in the PATH which I guess is the reason you did it as well :-)

**Comment by gitvasile** [comment]
I did a strings on the T-Kernel partition dump. Tons of interesting strings in there.
