### ISSUE TITLE
HDMI live output

### ISSUE THREAD

**Issue by rcorbari** [ottokiksmaler/nx500_nx1_modding#16]
Hi all,

before to buy the amazing NX500 now discontinued, could you please tell me if it outputs live real time video from the HDMI port?

I need to mount it on a drone for surveying and videos.

Thanks.

**Comment by ottokiksmaler** [comment]
HDMI out is 1080p but does not work in 4k and in high-speed video.

**Comment by rcorbari** [comment]
Thanks,

Is it a live recording output or just playback?

**Comment by ottokiksmaler** [comment]
Live

**Comment by rcorbari** [comment]
Thanks. So, as final note, if I shoot at 1080p up to 60fps the HDMI streams live video.

Differently, if I shoot at 4K the HDMI does NOT output any video, neither downscaled to 1080p.

Is it correct?

Thanks.

**Comment by ottokiksmaler** [comment]
1080p60 I have to check, 4k gives no output at all.

**Comment by rcorbari** [comment]
Ok thanks. This is a pity, I look forward to find someone that will hack the output as well :)
