### ISSUE TITLE
UI for NX hacks

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#18]
How about a bitrate/fps/resolution UI that looks a bit close to the png I included in my v2.0 mod?
In its default state it would show what is the current value for each accessible setting, and clicking on the setting would bring up a menu for the user to input the override value.

Basically there would be a sort of active area for each changeable setting. If not enough space, it might have a screen for bitrates, another with resolutions and another for fps, all looking a bit like the png.

Do you think there would be enough space on the screen for something like that?

I could write a C function that would take as args camera model, target "box" and desired fps/resolution/bitrate, while the interface would do the interface :-) and call it to set the values.

IMO this would look cool and be easy to understand for everyone - I hope.

Thoughts?

**Comment by ottokiksmaler** [comment]
Could you take a look at https://github.com/ottokiksmaler/nx500_nx1_modding/tree/dev/mod_gui

Everything works, but I should better test the installer scripts for all possibilities.

Also, sorely lacking in default cfg files for both cameras - this is where your magic will come :) - the buttons/checkboxes should activate specific bitrate/resolution mods?

Also, a question - should the mod announce it's presence and how? Currently two separate issues:
- keyscan - via popup or blinking SD card led (already in the code, but disabled right now)
- individual mods - might be an overkill

Sources are at https://github.com/ottokiksmaler/nx500_nx1_modding/tree/dev/mod_gui/src

**Comment by ottokiksmaler** [comment]
We should definitely make a better UI - more like "fn" quick-access-menu one - but it will have to wait for either me getting much better at using efl toolkit (not likely, just take a look at the code - it really is like that) or porting some other toolkit to the camera (this will mean bigger file sizes - much bigger).

**Comment by gitvasile** [comment]
just very briefly  - I am going to bed

1. NICE.
2. for me there are these types of scripts:
 - mods that are run one time at any time - say macro focus
 - bitrate-like mods that need to be run only on cold boot
 - silent-shutter mods that need to be run on every boot

Last two would need the checkbox but you need an option in the cfg to
identify between them. You need this because at a later stage there might
be more complex hacks that would slow down hot boot too much, with no need
if they were not destroyed by suspend. I class my bitrate backs amongst
these,

Regarding my hacks - I would like to shamelessly plagiarize your poke
program to implement my hacks like this:
hack camera:whichrate:newrate camera:whichres:newres camera:whichfps:newfps
example:

myhack nx1:pro1:137 nx500:pro2:110 nx500:video2:2550x1440

etc.

Would you object?

otherwise it looks very good!

rgds

**Comment by ottokiksmaler** [comment]
Actually, I think I could relatively easily adapt mod_gui to show title line at the top (explaining the choices), buttons below and possible cancel button at the bottom. One window to choose from resolutions and another for bitrates? And then it calls your program to do actual work?

**Comment by gitvasile** [comment]
announce should be a very brief popup at cold start and, if possible, a
permanent dot somewhere on the screen, so you know there's something there
non-standard.

If possible :-)

**Comment by ottokiksmaler** [comment]
Of  course not. It's open source after all :) feel free to do anything that can help you (might want to do better memory handling with malloc and friends though) 
Also going to bed, bye

**Comment by gitvasile** [comment]
bigger means slower :-( - usually

**Comment by ottokiksmaler** [comment]
I think we can combine resolution and fps choice into one window:
4k: 24, 30
UHD: 24, 30
2.5k: 24, 30, 60, 120 (?)
FHD: 24, 30, 60, 120
HD: 24, 30, 60, 120
That's 12 possible combinations, could be in a grid, rows for resolution, columns for fps
Bitrates are plentiful so they have to be separate
But, how do we actually implement this? We are overriding existing resolution/fps/bitrate options, right? So we first need to choose what we are overriding, then with what. You have a better understanding of this, what do you think?

**Comment by gitvasile** [comment]
are you on google hangouts - can you ping me on nxcameramods@gmail?

**Comment by ottokiksmaler** [comment]
:D
I was just experimenting with USB-OTG cable and NX500. telnetd on /opt survives USB-OTG cable plugging in and continues working (SD card is unmounted).
Unfortunatelly there are 3 modes for USB right now (available in /sys/bus/platform/devices/slp_multi/usb_mode/usb0/): f_mass_storage, f_mtp, f_sdb. While it's not impossible to create support, it would mean at least compiling the required kernel modules (should not be hard) and triggering the required mode (completely unknown). 

It might be worth the effort (not only mass storage, this could potentially allow for external audio, etc) and I'm willing to examine it in the future.

P.S. Sent you a ping on google talk.

**Comment by gitvasile** [comment]
Did you check dmesg to see if there are any messages?

**Comment by ottokiksmaler** [comment]
There are, but nothing unexpected. There needs to be a kernel module loaded and configured to produce anything

**Comment by gitvasile** [comment]
BTW, how is your NX500, all is well? Mine has a problem with the power button, it is a lot more loose than at the beginning.

**Comment by Tommixoft** [comment]
Hello misters.
Otto here is my suggestions, you may already though about, but as a user:

- All mods should have their own folder, in folder should e some info file which you could read and show in GUI it's name, version and so on.
- Users should be able to enable and disable mods without deleting files. You could create special named file in mod folder like enabled, to know if mod requires execution or not.
- All mods should have only 1 executable file (script which does all the work - so you always know that in MOD dir if there is file called ENABLE you execute file called.. run.sh or similar)
- Info file could contain Creator, mod name, mod version, mod category fields. so it will be easier to display mods in their own category (like MagicLantern)

by this design you solve many problems. Users can add their own mods just by creating dir with required files. Your GUI on run scans MODS directory for all subdirectories and loads info file for display purposes. 

Of course there is things like mod settings and so on, but this is i think easier for you to think most efficient way of how mod can tell what properties it has and what type of value should be set.

Regards.
