### ISSUE TITLE
NX USB OTG

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#19]
otto wrote:
:D
I was just experimenting with USB-OTG cable and NX500. telnetd on /opt survives USB-OTG cable plugging in and continues working (SD card is unmounted).
Unfortunatelly there are 3 modes for USB right now (available in /sys/bus/platform/devices/slp_multi/usb_mode/usb0/): f_mass_storage, f_mtp, f_sdb. While it's not impossible to create support, it would mean at least compiling the required kernel modules (should not be hard) and triggering the required mode (completely unknown).

It might be worth the effort (not only mass storage, this could potentially allow for external audio, etc) and I'm willing to examine it in the future.

**Comment by gitvasile** [comment]
first we need to figure out a way to see if hardware support is there - AFAIK to have OTG you need both HW and SW support.
I will take a look at the kernel configuration file when back home, who knows...

**Comment by gitvasile** [comment]
also did you try cat /proc/devices and dmesg?

**Comment by gitvasile** [comment]
Note to self: dig through available kernel device driver sources to hunt for otg references.
The idea would be that if the HW supports it, they would probably have included some level of kernel support. I would have.

**Comment by ottokiksmaler** [comment]
Also worth noting - Samsung shipped a number of smartphones that actually do support usb otg but don't have power pins connected (ie, requiring external power source to work) like s4 mini and the like.

**Comment by gitvasile** [comment]
close for now
