### ISSUE TITLE
Title name of this folder with hacks. NX500 & NX1

### ISSUE THREAD

**Issue by vinnie112** [ottokiksmaler/nx500_nx1_modding#2]
Small detail. Maybe change the folder name with the hacks from nx500. To a name like: 'NX1 and NX500' . Makes more sense to me.

Great hacks by the way. Awsome people who're making this possible!

**Comment by ottokiksmaler** [comment]
Thank you for your kind comments. 

I have changed the name of the repo, but I can only test (and develop) for NX500. Mods that are model dependent will be clearly marked as such.

Best regards

**Comment by vinnie112** [comment]
Hey,

Aah I get it. I'm so excited for this stuff! Wish I could develop myself. I'm available for testing hacks, if you need. I own the NX1 camera.

Best regards

**Comment by PaulInAtlGA** [comment]
First time interacting in github, here.  Just want to plead on behalf of the majority of we NX owners that are interested in these hacks, but see no basic step-by-step instructions.  We need a bottom rung or two on the latter for us to get started.  I found one post that shows how to gain camera control from a PC, but nothing on the main page about this, or how to actually use all these scripts, once you're that far.  Can a section be added to the main page about this, please?

**Comment by ottokiksmaler** [comment]
Hi Paul,

I have added TL;DR section in the Readme (front page) with direct link to "introduction" section on customizing keys [here](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/README.md#tldr---i-want-my-camera-hacked---what-to-do).

**Comment by PaulInAtlGA** [comment]
Thank you so much, Otto.
