### ISSUE TITLE
NX-KS - discussion

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#20]
@KinoSeed Hi, IIRC you can use

```
st app disp [lcd|evf|auto]
                          - control display select
```

in your scripts for NX1 to switch to back LCD.

**Comment by ottokiksmaler** [comment]
> some have reported slower touch-functions, which may be related to key-scan's capturing the touchscreen (I don't know, so it's just speculation), so maybe we can have capturing from the touchscreen to be enabled only when needed if indeed that turns out to be a problem.

keyscan does not intercept screen touches - it uses very efficient select system call (it's not polling constantly, it tells the system to be notified when there's something happening on monitored files) to monitor for two /dev/ files representing back and top physical keyboards (as a consequence it consumes next to no resources for this). It does start another thread that goes off every second but only checks the timer to see if it was suspended in the mean time. I have put this to disabled when running keyscan from SD card (as it's killed on sleep anyway). I have also modified it to kill pressed EV button on starting external scripts as some of the scripts get started and might steal key events from keyscan so it does not detect that EV is released so it tries to do stuff in background (it thinks people are using EV+something when they press something) - this is very unlikely but I have added either way. The catch is that no one active here has a NX1 so it's a bit tricky to develop and test for ;)

RE: systemd 
You can add your service and it works on boot - but this camera does not boot at all :) it just resumes from sleep so your systems service/target is never executed - that's why I had to hook on bluetooth in the first place. I have rebooted to recovery mode (it just checks filesystem AFAIK) and it seems to do full boot on the camera with service starting, etc, so might try that (it takes ~30s to do so, don't panic). It's documented in issue 13 (heh) but here's the interesting part:

>Don't know, but last night I did boot to recovery (via systemd target recovery) and it fully boots, taking longer time, checking filesystem (as it was changed a long time ago in factory) and di-camera-app has pid 249 (usually 247). I did not perform regular shutdown but popped out the battery when I was finished, as I didn't want to update the hibernation image (not sure it would do it anyway, but just to be sure). 
>So, I guess this is one possible way to experiment with the system without the fear of damaging functionality (battery pop out and we're back to hibernated image).

Not sure about disabling logging - might give it a try (have to see what and how works).

**Comment by KinoSeed** [comment]
`st app disp [lcd|evf|auto]` was used in v1.40 for LCD-off recording, and I had a bad surprise.
This choice is persistent after camera restart, which for NX500 means starting with a black screen and no way to even turn on telnet :) 

But indeed it may be better for NX1 to auto turn on the LCD if they activate the menu.

**Comment by KinoSeed** [comment]
systemd - since it doesn't really boot, it must be.. "resuming"
maybe something like this will work:

```
[Unit]
Description=<your description>
After=suspend.target

[Service]
User=root
Type=oneshot
ExecStart=<your script here>
TimeoutSec=0
StandardOutput=syslog

[Install]
WantedBy=suspend.target
```

**Comment by KinoSeed** [comment]
By the way, I added a Kill Switch for the keyscan (as it was requested), but I noticed, that after a killall, it won't restart again (it gives a message that it's running, when it's not anymore)

**Comment by KinoSeed** [comment]
systemd  - tried to catch all sorts of triggers - no result
made even a timer, enabled, started, working, but does not survive "sleep"
it's like the "memory" is getting rewritten and the system does not even know it's reset, yet di-camera-app restarts (or rather reinitializes), and it in turn triggers the BT hook.

**Comment by gitvasile** [comment]
Kino Seed - this is not new - please check other older closed issues.
The system goes to sleep and does not re-read systemd config upon wakeup.

I know how to create a hook that will run immediately: I can intercept the di-camera-app resume thread (I identified the right place) and run another program but it is far from trivial: I need to manually assemble the system call in a memory zone that is otherwise unused, and then return control to di-camera-app.

There are other alternatives: messing up with the hibernation image stored in one of the partitions, but I personally won't touch it with a 10 foot pole on my own camera.

This is one of the reasons for running the "burner" poll BTW.

**Comment by KinoSeed** [comment]
thanks, I'll take a look

**Comment by ottokiksmaler** [comment]
To restart keyscan after force killing it you need to remove keyscan.pid file from /tmp as well.

**Comment by ottokiksmaler** [comment]
I meant 
st app disp lcd
To force lcd on - so you can display popups to users.

**Comment by ottokiksmaler** [comment]
@KinoSeed did you try recovery target for systemd?

**Comment by KinoSeed** [comment]
I already put "st app disp lcd" as an alternative.. actually don't want to risk it so it's rather:
[[ $(echo $(st cap capdtm getusr MONITOROUT) | grep LCD) > ""  ]] || { $(st app disp lcd &&  sleep 1 ; }
(adding a second delay just in case NX1 need some time to switch from evf to lcd)
it will be in the next version

**Comment by gitvasile** [comment]
di-camera-app does not restart - it resumes :-)

**Comment by gitvasile** [comment]
I think recovery target is pretty safe as long as the hibernation image is not touched. What I am afraid is of touching the hibernation image because the camera always cold resumes from it - it never cold boots unless you set recovery target. And you cannot have access to set recovery target unless you are already booted :-(.

So if you mess up with the hibernation image, the camera goes to Samsung for repair.

I know there is a way to recover from this - have the bootloader.bin and nx500.bin on a sdcard, but these are only available to Samsung :-(

**Comment by KinoSeed** [comment]
are you sure it "resumes"?
it does after all load the Blootoothd again (I assume that's the handy work of di-camera-app)

**Comment by gitvasile** [comment]
yes I am sure. Bluetooth is turned off when going to sleep. Also there is a final proof: I never change the FS, only patch memory for the bitrates.

If the app would be restarted, the mod would be lost on resume and it is not.

**Comment by KinoSeed** [comment]
no luck with:
WantedBy=recovery-mode.target

actually, di-camera-app.service should be run only after "auto_run.service"
which in turn (ahead of it) does this:
ExecStart=/bin/sh -c 'while [ ! -e /tmp/.wm_ready ]; do sleep 0.1 ; done; sleep 5;echo test > /mnt/mmc/arun '

I've never seen "arun" on the sdcard, so I guess there's never a real "boot" indeed.

**Comment by KinoSeed** [comment]
Decided on using /opt/home/ as it does not require removing the write-protection.

but from at least hibernation it seems it does "cold boot".
any ideas how we can force a "sleep" instead of hibernation, and live to tell the tell on wake-up?

**Comment by Tommixoft** [comment]
@KinoSeed  - i saw your mod have hack to sleep to save battery life. i do not use it, but i have little suggestion:
Camera ALWAYS focus, even if it's not in continues focus mode, this uses battery a lot, maybe you want to add into your battery saver hack add option to switch to manual focus, and on wake -to the previous one?
I want this camera to use as less battery as DSLR uses :) i can use my canon whole day on and it will last, but this nx500 sucks energy quickly :)
If you look at TOP with lens cap on you will see cpu usage drops in half compared to when cap is off. Would be maybe beneficial to turn off face detection on "sleep" (i mean your saver mode).

**Comment by Tommixoft** [comment]
@KinoSeed  do you know offsets and values to replace 4k (not UHD) video mode with 2.5k?
Would appreciate :)

**Comment by ottokiksmaler** [comment]
Camera only focuses when told to. This includes face  detection, auto mode, etc. Go to PASM mode and set AF to S-AF (single) and it will not focus continuously.

**Comment by Tommixoft** [comment]
> Camera only focuses when told to. This includes face detection, auto mode, etc. Go to PASM mode and set AF to S-AF (single) and it will not focus continuously.

Sadly but it focuses ALL the time. i set my focus to SINGLE - it still focuses even if i do not half-press button. only when i set to MANUAL it stops focusing.

**Comment by ottokiksmaler** [comment]
Check for face detect

**Comment by KinoSeed** [comment]
@Tommixoft , check the posts on dpreview, I think i posted all the possible values there (I don't have them at hand at the moment)

**Comment by Tommixoft** [comment]
Well looks like autofocus works in ALL modes no matter what focus system is enabled, only manual disables autofocus which is super stupid. This drains battery very quickly, stepper motor in lens works all the time, not to mention all other processes who analyses visible data

@ottokiksmaler  - yes indeed when i disable face rec. it stops autofocusing... SO why it focuses on things who are not faces...stupid :D

**Comment by Tommixoft** [comment]
@KinoSeed  - you should start uploading changelogs to your mod, you change it every few hours and no changelog. Only russians do this :)

**Comment by KinoSeed** [comment]
They must be very smart then : )
I do write the major change/update in the update field, as well as in the forum.
Detailed changes will take me just as much time as making the next release, and I don't see that need.
Essentially it is designed to be as simple and yet most useful as I can make it, so you shouldn't need the change-log, just to install the last version. ; )

**Comment by ottokiksmaler** [comment]
Tommi, as this is github, you can always see individual commit comments, etc, like here 
https://github.com/ottokiksmaler/nx500_nx1_modding/commits/master/NX-KS.zip
