### ISSUE TITLE
Auto running scripts

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#21]
@gitvasile @KinoSeed 
Currently there are two types of auto run scripts:
  - Ones that need to run on cold and warm boot (sleep/resume) - silent shutter, focus position, etc.
  - Ones that need to run only on cold boot (battery pop out) - like bitrate ones

In order to not complicate everything even more, I would suggest to separate them by convention by assigning them names in following fashion:
  - Sleep/resume scripts - names start with "warm_", others - names start with "cold_"
  - Sleep/resume scripts - names start with "resume_", others - names start with anything but "resume_"

I think calling them "warm_" and "cold_" would give us a clearer layout and prevent confusion, but both work for me.

What do you think?

**Comment by gitvasile** [comment]
Your proposal works for me - at least for the time being :-) (warm_ and
cold_)
Added benefit: both prefixes have equal number of letters :-)

**Comment by gitvasile** [comment]
BTW welcome back :-)

**Comment by ge0rg** [comment]
I would rather prefer `boot_` and `resume_` as name prefixes, using terms well-known in the IT field to reduce confusion. An experienced computer user can more easily understand these than what "warm" and "cold" might refer to.

P.S: I'm only skimming all the interesting discussions taking place, as I don't have any time (officially). But you are doing awesome work!

**Comment by gitvasile** [comment]
But that is exactly the point. The camera never actually boots (under
normal circumstances).

It either resumes from suspend or resumes from a hibernated state.

So both are actually resume.

**Comment by KinoSeed** [comment]
Having "resume_" only sounds better/simpler to me.
Then the "off" script will be like  "off_resume_" or simply "off_"?

**Comment by ge0rg** [comment]
@gitvasile whoops, you are right. What about `hibernate_` and `sleep_` then (though waking up from these states actually is the opposite)? Maybe cold and warm aren't that bad after all ;-)

**Comment by gitvasile** [comment]
there are two types of resume: cold and warm. I like Otto's version best - it is clear and concise. Alternatively ge0rg's suggestion works, but I prefer Otto's. Guess it's a matter of personal preference so AFAIAC I'll let Otto to decide.

**Comment by KinoSeed** [comment]
To be the devils advocate - is it really necessary?

I would rather have bitrates update ahead of anything else, just to have them ready ASAP.
Also I would have the bitrate mods reload each time, just to "make sure" if nothing else.
And they take less than a second to get modded.

The rest of the cold_ scripts are 1 or 2  - the rec-limit and maybe the 2.5K mod?
feels like separation of the scripts although may be more efficient will only increase complexity without much effect on performance. (correct me if I'm wrong)

**Comment by gitvasile** [comment]
I can not see in the future to determine if there will be "heavy" mods required on cold resume.

I would therefore assume there will be and prepare for it by separating the mods.

Bitrate mod is only needed on cold boot, guaranteed not needed on warm boot.

**Comment by ottokiksmaler** [comment]
FWIW, there's nothing stopping anyone calling bitrate scripts warm_something.sh so it gets executed every time. Off scripts would have to be called off_warm_something.sh.

**Comment by Tommixoft** [comment]
@KinoSeed 

> "..feels like separation of the scripts although may be more efficient will only increase complexity without much effect on performance. (correct me if I'm wrong)"

Yes you wrong and i think you know that :D. On average 1 script to execute 1 simple command takes 1 sec (if message boxes is not used). If there is more than 5, in your case you add gazillion scripts in your mod, this really makes diferencine to run only those scripts who are overwritten [killed] in ram. 
Adding more than 10s to completely load camera when ON is huge time span. This camera is already very bad with battery life[and it's not battery fault it's crappy SW fault], so people like me who turning off and on to save it-would die from those loading times :D
Also i had few times that executing scripts just hangs camera, especially if camera is in photo/video display mode (when you look at taken picture). SO the less of them-the better performance.

**Comment by Tommixoft** [comment]
@ottokiksmaler  Otto can you keyscan run autostartup scripts in multi-threaded fashion? Now you waiting for command to finish and then executing second script, why? why you need return if you do nothing with it? 
Maybe you can run scripts [files] async? This would greatly speedup load time [if cpu is not shit of course].

**Comment by ottokiksmaler** [comment]
It starts them in sequence on purpose. If you want something that forks to background just put & in the script,but beware that multiple instances of st or similar will either block or bomb if run in collision.

**Comment by KinoSeed** [comment]
@Tommixoft, the main delay which comes at starting comes from the hook that is used - the BT-mod, which starts 6-7 seconds after you turn your camera-on. Your claim that "On average 1 script to execute 1 simple command takes 1 sec" is simply not based in reality, and I suggest you check this yourself. (you can do it even over telnet if you wish)

**Comment by Tommixoft** [comment]
@KinoSeed   

> the main delay at camera start, comes from the hook that is used - the BT-mod

I don't know if i agree. i do see when bt is on and i only count time from that moment, not from turning on camera. 
Anyways i think Vasile's idea of putting mods into application is good. Of course app do the same as scripts -only executes them in app instead of script file. But maybe Otto could build additional app which would have most popular mods, settings file (app should be able to save to it) and it could have the same checkboxes, buttons but no scripts. This one could use people who dont want to mess with scripts.

But again - there is only few mods so crating app is well..overkill. I doubt that NX will have anything else than now (except maybe ability to put custom hibernation image). And seeing that only few people working on this - just proves - nx is dead, it have potential, more than canon but somehow nobody wants to join the party with Otto, Vasile..on  haking. Nice that KinoSeed  you made huge pack of hacks..but 3 people - looks like it's really not much.

> Your claim that "On average 1 script to execute 1 simple command takes 1 sec" is simply not based in reality, and I suggest you check this yourself.
It's based purely on reality, using telnet is NOT reality. 1 second is the least time, i think it takes more. ST commands takes more than  1 sec. usually 2 or more.
