### ISSUE TITLE
Timer and bluetooth doesn't work when focus stack installed

### ISSUE THREAD

**Issue by Pascal1965** [ottokiksmaler/nx500_nx1_modding#25]
Hi,
I  installed focus stack in my NX1. It works fine but when I try to use bluetooth or timer, it doesn't work anymore.

**Comment by ottokiksmaler** [comment]
Hi, how did you install it?

**Comment by Pascal1965** [comment]
I install it  according to your advice : "unpack sd.zip file to your SD card root, put focus_stack file in scripts folder on SD card and create/edit file named EV_AEL.sh (so SD/scripts/EV_AEL.sh) to contain:
/mnt/mmc/scripts/focus_stack"
When I use another SD card without focus stack, blutooth and timer work.

**Comment by ottokiksmaler** [comment]
That's quite old version, you should probably use this one https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/NX-KS-Readme.md
It is much more than just what's in original one but it's newer.

**Comment by Pascal1965** [comment]
Ok, I just downloaded "NK-KS.zip". Is it a soft modification or does it change the firmware of my NX1? Can I use a normal SD card too?
Thanks

**Comment by ottokiksmaler** [comment]
It modifies you camera so you can use any card and have mods working. If you need to remove it midst unpack it again to card and restart camera with that card and choose Uninstall

**Comment by Pascal1965** [comment]
Ok Otto, I don't see in the "Readme.md"  the uninstall process. Are you sure that there is one in the NK-KS.zip ?

**Comment by ottokiksmaler** [comment]
My bad, you can actually remove it from camera without unpacking to SD card

EV+EV brings the main menu (double click EV)

"Uninstall" is in Settings

**Comment by Pascal1965** [comment]
Ok so I double click EV and select "Uninstall" and all is deleted and I comme back to the original firmware. That's right Otto?
Waiting your answer, let me share this picture I took using focus stacking (60 photos)
[](url)https://www.flickr.com/photos/133437461@N06/26757370542/in/photostream/lightbox/

**Comment by ottokiksmaler** [comment]
Yes. If you are on nx1 then it's EV+OK. But, it's even better, if you turn Bluetooth off and then restart the camera by popping the battery out - you are running stock firmware until you turn bluetooth on.

**Comment by ottokiksmaler** [comment]
Flickr now requires email for access? Funny.

**Comment by Pascal1965** [comment]
Ok Otto, I'll try this new version. I hope timer and bluetooth will work agin after that.
Sorry, I didn't know Flick requires email...
[http://img15.hostingpics.net/pics/31574726757370542ffa632199ao.jpg](url)

**Comment by Tommixoft** [comment]
WOW.. gross! :D

2016-05-09 16:02 GMT+03:00 Pascal1965 <notifications@github.com>:

**Comment by ottokiksmaler** [comment]
Impressive!

**Comment by Pascal1965** [comment]
Impossible to do that without your software ;)

**Comment by ottokiksmaler** [comment]
I didn't realize you took that with my program :) so happy when I see my work is being used. Thank you for posting
