### ISSUE TITLE
dynamic shared libraries loading and calling their functions

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#26]
Otto, here's an idea - instead of statically linking to the libraries we want to call functions from, how about loading them dynamically like in the attached file.

There's only a small snag: compiles but when running it gives me
`-sh: ./calldyn: No such file or directory`

[calldyn.c.txt](https://github.com/ottokiksmaler/nx500_nx1_modding/files/253621/calldyn.c.txt)

Thoughts?

edit: works if compiled with this:
`arm-linux-gnueabihf-gcc -o calldyn calldyn.c --sysroot=../../nx500/mnt/rootfs/ libdl-2.13.so -Wl,-dynamic-linker,/lib/ld-2.13.so`

**Comment by gitvasile** [comment]
updated source - calling get_pref_long just like your example.

[calldyn.c.txt](https://github.com/ottokiksmaler/nx500_nx1_modding/files/253648/calldyn.c.txt)
`[root@nx500 bin]# ./calldyn 
Hello from main!
pref_get_long(3, 0x208) = 1244
[root@nx500 bin]# prefman get 3 0x208 l
[sysrw] in memory: 


 value = 1244 (0x000004dc) 
`

**Comment by gitvasile** [comment]
hopefully this will allow "generic" calling without having to compile against the libraries.

**Comment by ottokiksmaler** [comment]
Excellent idea, will make source a bit more ugly but it will take care of compile time issues. Thanks!

**Comment by gitvasile** [comment]
Otto, I did some more preliminary work on this but again I get runtime crashes when running this on the NX500.
care to check this: [https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/dynamic-library-function-calls/calldyn.c](url)?
We can discuss in there and I'll close this issue.

**Comment by ottokiksmaler** [comment]
Not at computer until tonight, cannot add comment to commit from mobile site (or I don't know how).

**Comment by gitvasile** [comment]
No rush :)

**Comment by gitvasile** [comment]
ok sorted, it was not related to compilation.

**Comment by ottokiksmaler** [comment]
I'm magic like that, as soon as people explain me their problem they magically find the solution. Happens all the time :)

**Comment by gitvasile** [comment]
you back @ computer?

**Comment by ottokiksmaler** [comment]
Not until ~22 CET

**Comment by gitvasile** [comment]
ok

**Comment by gitvasile** [comment]
v1.0 final [here](https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/nxcalldyn)
HTH

**Comment by gitvasile** [comment]
@ottokiksmaler Ok to close the issue?
