### ISSUE TITLE
Auto Exposure Bracketing

### ISSUE THREAD

**Issue by PeterNX** [ottokiksmaler/nx500_nx1_modding#28]
First of all I wanted to say thanks to everyone who is making this new features possible. The NX500 is already a great camera and you are helping to make it even better! 

However one feature I am missing is a better AEB Mode. On NX500 you are limited to 3 pictures where on the NX1 you can shoot 5 pictures at once. So I wondered if it is possible to enable the AEB mode from NX 1 somehow?

I am sorry if this is the wrong place to ask such a question. I am fairly new to github.

**Comment by gitvasile** [comment]
https://github.com/ottokiksmaler/nx500_nx1_modding/issues/23

**Comment by ottokiksmaler** [comment]
This is exactly the place for such questions :) 
As you can see we are already working on it but might take some time as the are other things to finish first.

**Comment by PeterNX** [comment]
Ah this is good news. I already read the roadmap but must have skipped that point. I wish I could contribute somehow but my skills are not nearly enough... Well at least the next time you start any funding, count me in ;)

**Comment by gitvasile** [comment]
You did not miss anything - I thought it would be useful and feasible when I read your request so I added it.

But I will stress: **no guarantees and do not ask for ETA**, both me and Otto have our lives too.

**Comment by Tommixoft** [comment]
Who uses bracketing?? Use raw and you don't need any bracketing.
There gazillion times important thing to work on than this one who is usless. really, who uses jpg these days?

**Comment by PeterNX** [comment]
@gitvasile: Then thank you very much for adding the request :) I fully understand that there is no guarantee and things need time. I can only repeat myself that I am already impressed about your effort!

@Tommixoft: I also understand that everyone has their own priorities. In fact you are right that a single raw is enough most of the time (and I am already using raw). But there are also special situations where a single raw won't give enough dynamic range to capture a scene (I am speaking of HDR images for example). I just think that an improved AEB mode could help a lot of people. And if it might be doable.. the more the better, isn't it? ;D

**Comment by Tommixoft** [comment]
@PeterNX  - raw will always be better than multiple exposure jpgs :) Atleast when we talking about 3-5 files. yes if you do 12 exposures MAYBE it will benefit a bit but still not sure.Just shoot bit underexposed raws and will be good. But yes this is everyone's preference.

To create what you ask-Otto would have to create new GUI, cause right now gui is VERY limited. Only buttons and checkboxes. 
Anyways... i just think that we don't have car yet and people asking to change wheels color :D
