### ISSUE TITLE
Video output for live preview (Video) for Samsung NX500

### ISSUE THREAD

**Issue by Fickert07** [ottokiksmaler/nx500_nx1_modding#3]
Sorry I am new to Github and am not sure if I am posting this in the right place, but I am using my Samsung NX500 for aerial Photorgraphy and video. I use an hdmi to av converter to take still photos in 4k which works great. But to record video with live preview I can only go up to a 1080p 24fps recording resolution, since that is the resolution it is pushing through the hdmi port. Is there a way to get around this to be able to record in 4k 24fps with a live preview out of only 1080p or lower?

Thanks

**Comment by ottokiksmaler** [comment]
None that I know of. NX1 can record 4k while streaming out to hdmi, but nx500 cannot. Maybe use additional camera for monitoring the rear LCD? An ugly hack for sure, but only thing I can think of.  Also, hdmi out works in stills mode FWIW.
