### ISSUE TITLE
work in progress

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#33]
I'd like to keep this one post/contributor only. Please post requests [here](https://github.com/ottokiksmaler/nx500_nx1_modding/issues/31). **active** means someone is working on it and, for now, plans to continue working on it. Otherwise there was some time spent on it, but currently there's no active development/effort. Lists are **not** ordered, **no** ETA and **no** result guarantee.

**Comment by gitvasile** [comment]
- [ ] **active** - **burner cam received** - better way to launch mods from hibernation, with override on boot with key pressed
- [ ] remove hardcoded time limits for NX500
- [ ] rsync backup when connected to home wifi
- [ ] uncropped 4K for NX500
- [ ] video LUTs
- [ ] break into T-Kernel to see if more video modes are feasible
- [ ] disable video NR - update: good chance that video NR is already factory disabled
