### ISSUE TITLE
TBBAF

### ISSUE THREAD

**Issue by stf1x** [ottokiksmaler/nx500_nx1_modding#36]
Hi, Sorry for the late reply. Yes, it also does the original function - that's why it's so difficult to do for nx500 - the only button that's supposed to be used pressed down is EV and I can't use that.

May 11, 2016 at 04:59
stf1x
I will test again TBBAF once I have time, I assume I can still start it from a telnet session and have a look at the log files on SD, are they produced also if not in factory mode ?
"there's no way to make it work on nx500" 
All the mod functions are currently on key that are not used by samsung, like EV+ something, correct ?

how does keyscan work actually for AF ON ?
(if (bbaf && NXKEY_AFON == (int)ev.code && 1 == ev.value))

does it perform the original function of the button as well (for example C-AF) or is the original function not called at all and only the replacement is executed instead ? (here: execute_script("/usr/bin/st cap capdtm setusr AFMODE 0x70001"))

May 10, 2016 at 20:05
otto k
I tried everything but there's no way to make it work on nx500 :( there just is no button that behaves like af-on. 
When an application crashes there is a set of log files made on SD card. You could upload them somewhere. 
It is quite possible it behaves better in factory mode, they are very different, but I have no way to test any of it. Sorry. I have an idea I'll try over the weekend and get back to you.

May 6, 2016 at 06:00
stf1x
drime5 login: root
[root@drime5 ~]# opt/home/scripts/keyscan /dev/event0 /dev/event1 /opt/home/scripts/ bbaf
OLD PID: 0
PID: 702
BB-AF ON
704 (process ID) old priority -20, new priority -20
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
/opt/home/scripts/pokemon: line 106: [: too many arguments
704 (process ID) old priority -20, new priority 19
UserData is set
[ 1: 238.811510] I/CAP_LV (A7 54): [Live] PManager]CLiveviewPerformanceManager init
UserData is set
UserData is set
UserData is set
UserData is set
UserData is set

May 5, 2016 at 21:47
hallo otto, i did some more testing with the BBAF functionality in the new envoronement (1.47 w/o factory mode) by invoking keysscan bbaf via telnet: Sometime it works fine, somtime the camera crashes (reboot). 
I can not see a pattern.

Kino has added it to the package now, but I rather test via telnet over the next days, since invoking it via the UI caused me and another test problems, and I were scared that we had bricked the camera. Kino fixed it by making a patch which will kill the keyscan before installing, which solved the issue.

Below is a log of a session on NX1 that crashed.
Could you maybe do:
1) add a key combination for the NX500, so more ppl can test it.
2) Anything else that can facilitate the degugging
3) Have a look again at the relevant section in the keysscan code, I had the feeling it was a bit more stable in factory mode

May 5, 2016 at 21:46

After some time of usage (5 minutes) it kind of mini-crashes or resets (all symbols of the UI disappear for a few seconds, then the camera is back).

Could you add these commands to update symbols/icons on the UI and show the modes you are activating (MF or SAF)?
I think these are commands like the below which I got by looking at the code from focus_stack.c:
run_command("/usr/bin/st app nx capture af-mode manual\n"); // show manual focus mode

Apr 11, 2016 at 21:54
It works :-) 
You're a star!

Apr 11, 2016 at 05:54
otto k
I have updated it now, could you test?

Apr 10, 2016 at 21:46
Oops, I have a wrong key code, thank you :) I will make a corrected version tonight (I'm at a picnic right now) and send you a message.

Apr 10, 2016 at 11:43
stf1x
It doesn't work on ny NX1, the "AF ON" button still does behave as before, i.e. focus and lock in SAF and CAF in CAF. When I press the shutter it re-focuses. 
Have you linked it to the right button? NX 500 / 1 have "AF button", only NX1 has "AF ON" button.

If I use your debug option I get 188 for the "AF ON" button.
In can't see 188 when I look at keyscan.c code #defines.

How is it suppose to work on the NX500, I can test it there ?
Which action/key is

[root@drime5 scripts]# /mnt/mmc/scripts/keyscan_bbaf /dev/event0 /dev/event1 /mnt/mmc/scripts/ debug
DEBUG ON
Opening inputs /dev/event0 /dev/event1
PRESSED 125 <- shutter half press
RELEASED 125<- shutter half press
PRESSED 188 <- "AF ON" button NX1
RELEASED 188 <- "AF ON" button NX1

PRESSED 125 <- shutter full press
PRESSED 126 <- shutter full press
RELEASED 126
RELEASED 125

Apr 10, 2016 at 11:25
otto k
It should be continously auto focusing while AF is pressed and when you release AF button half press should not refocus, just meter, full pressing should take photo as usual.

Apr 10, 2016 at 07:39
stf1x
By the way I have also an NX500, so could test it there, but again not sure what key to press to activate it and what behaviour to expect back

Apr 10, 2016 at 07:19
Hi,
This is what I did
1. Create the SD card from https://github.com/ottokiksmaler/nx500/blob/master/sd.zip
2. added keyscan_bbaf
3. boot from SD
4. telnet as root
5. run killall keyscan
   [root@drime5 ~]# /mnt/mmc/scripts/keyscan_bbaf /dev/event0 /dev/event1 /mnt/mmc/scripts/ bbaf
6. Got back 
   BB-AF ON
   UserData is set
7. what now ???

Apr 10, 2016 at 07:08
sorry, what am I suppose to test ? 
what have you implemented and what action shall I test ?

Apr 10, 2016 at 06:35
otto k
Yes, that's it, does it work?

Apr 10, 2016 at 04:58
stf1x
Re: NX500/NX1 - customizing function of keys (stf1x)

Anyway I was able to follow you instructuctions from the last message but not sure what I am suppose to test. Do I need to test a functionality on the camera (NX1) itself ?
I got this:
[root@drime5 ~]# killall keyscan
[root@drime5 ~]# /mnt/mmc/scripts/keyscan_bbaf /dev/event0 /dev/event1 /mnt/mmc/scripts/ bbaf
BB-AF ON

UserData is set

**Comment by stf1x** [comment]
otto, I just migrated the TBBAF thread to this platform

**Comment by stf1x** [comment]
otto k • Senior Member • Posts: 1,370
Re: I don't like TBBAF implementation (and OIS is not always engaged).

Can't have disabled half press auto focus - that's the issue with samsung implementation. Right now, the only way to *emulate* nikon like bbaf is to :

1. Switch to caf when afon is pressed

2. Switch to mf when it's released

If you mask the S1 button (half press, you can mask buttons) the camera does not capture the image. If you don't mask it the camera will refocus on half press. It's dumb but it is what it is.

There might be another way to do it but there's no way for me to know or try on nx500.

**Comment by stf1x** [comment]
otto, since you mentioned that the keyscan still does the original button function, I don't think it makes sense to perform _"1. Switch to caf when AF ON is pressed"_ since this is what the AF ON button does anyway on the NX1. 
1) I suggest to remove this part and to only execute "_2. Switch to MF when AF ON  it's released"_
3) Could you update symbols/icons on the UI and feedback to the user the modes you are activating (M AF)?
If you release a keyscan_tbbaf version (binary) here I can integrate it into the mod package myself and test it.

**Comment by stf1x** [comment]
If you can query the state the AF is currently in, you may have to activate C AF when AF ON is pressed, since once in MF, pressing the AF ON button does not perform anything. 
Also in case you trigger an action via keyscan, what is executed 1st, the original function or the code from keyscan ?

**AF ON pressed:** 
If (camera is in MF ?) 
{ switch to CAF; perform the original AF ON function}
Else
{ perform the original AF ON function}

**AF ON released:**
Switch to MF

**Comment by ottokiksmaler** [comment]
Unfortunately checking the current state of AF takes almost the same time  setting the state does so there is no penalty for just setting it blindly.

**Comment by ottokiksmaler** [comment]
It's multi thread environment, there's no guarantee what gets executed first, but keyscan is smaller and faster than camera ui handler  so it works out in the end.

**Comment by ottokiksmaler** [comment]
I have another approach but I would need someone to test it on NX1, are you willing? It would involve running a small script to mask half shutter but I'm not certain if it works the same way on nx1.

**Comment by stf1x** [comment]
I can not test for 1 week as I am travelling.

**Comment by ottokiksmaler** [comment]
Ok, enjoy your travel, hopefully, there will be a working tbbaf on your return :)

**Comment by stf1x** [comment]
OK, there is this long thread on dpreview ..... someone brought up the AFL feature (that is also implemented in a buggy way in samsung, but it does lock the focus on HS and FS)

keyscan-option
Instead of doing MF on "AF_ON press" and CAF on "AF_ON release", could you do "ALF on" on "AF_ON press" and "AFL off" on "AL_ON release" ?
AFL=auto focus lock function of the camera.
That would be in the keyscan.c

masking-option:
1)Put the camera in "release mode" (which should disable refocusing on full shutter (FS) press) 
2) Enable the TBBAF mod from the NX-KS (which should disable refocusing on half shutter (HS) press) 
problem now is that FS does re-focus suddenly in this setup:  half shutter does not refocus anymore, full shutter always focuses. This is odd, can you explain that ?
When you mask (the S1, HS), do you disable the actions of thr key press event completely ?
