### ISSUE TITLE
PTP/MTP mode via scripts?

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#37]
Is it possible to enable PTP/MTP mode without using factory mode, but rather via scripts? USB storage mode is pretty dangerous you can damage file system if you unplug usb without safe ejecting..so i think PTP/MTP mode is safer.

**Comment by ottokiksmaler** [comment]
Tried everything - not working. When I have time I will try to compile a new kernel module but that will take some time.

**Comment by Tommixoft** [comment]
@ottokiksmaler  wow -thanks for even trying. Just never had camera which mounts card as a disk. I always was using canon and it uses MTP..it slower but more safe.
of course it's easy to fix file system corruption in card, nothing will be lost, but anyways.... - i think useful  :)
