### ISSUE TITLE
NX500 4k crop

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#40]
Last night I was on dpreview and saw [this](http://www.dpreview.com/articles/9872942252/samsung-nx500-firmware-upgrade-improves-autofocus-and-enhances-video-features) of which I quote:
> The NX500 will now read out a larger area of the sensor, which the company says will improve 1080/60p video quality.

I take this means the crop is NOT hardware.

**All ye nx500 video crop haters, rejoice!**

**Comment by ottokiksmaler** [comment]
IIRC nx500 was severely line skipping in first version on 1080p video leading to ugly look (especially with super low bitrates) so they fixed it in that update. Not sure it applies to UHD.

**Comment by vasile-gh** [comment]
@ottokiksmaler to me, **larger** means wider and higher (i.e. a bit less crop or wider view angle with same lens).
