### ISSUE TITLE
stop wasting time on new FW

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#41]
Why you waste time on new FW? trying to do the same what is already done? Those who upgraded -its their problems, not yours.

**Comment by vasile-gh** [comment]
I will do it anyway for me (I want Android communications to work, and in a way sanctioned by Samsung) so I might as well share my results :-)

**Comment by Tommixoft** [comment]
For me android works good. im on 5.1 not 6, but anyways. I just see how much you both putting effort... and now again from the beginning do the same... just sad.

**Comment by vasile-gh** [comment]
not exactly from beginning - now I know where to look :-) - big advantage.
