### ISSUE TITLE
USB remote shutter release for video recording including pause/resume

### ISSUE THREAD

**Issue by teleV2** [ottokiksmaler/nx500_nx1_modding#42]
I would like to ask if it is possible to modify usb connection.
My objective is to control 'video record button' and 'ok button' remotely via USB connection not via Samsung App using bluetooth.

If any of below is possible, it will help many videographers using a gimbal or a stabilizer.

1. triggering buttons using USB signals for pin 1 & 4.
NX1 has a remote shutter release only for taking pictures not for video recording.
The USB connection is simple : ground D+ (pin 3) and the camera focuses, then ground D- (pin 2) and the shutter is triggered. Since there are no functions for pins 1 & 4 (pin 5 is ground), I am wondering if it is possible to trigger 'video record button' and 'ok button' by using these two pins.

2. remapping the USB signal inputs to trigger 'video record button' and 'ok button'.
If 1 is not possible, how about remapping for the pin 2 and 3 for 'video record button' and 'ok button'?

3. Or switch the function of the 'shutter button' and 'video record button' and 'half-press shutter' for 'ok button' in the system.

1 or 2 are not meddling the function of physical shutter button on the NX1 or NX500 so it is great I can still use the buttons whenever I want to take a picture while 3 probably changes the function of the button in the system level.

reference for remote shutter release : http://www.instructables.com/id/Samsung-NX-DSLR-Camera-Trigger-Cable/

Thank you very much for reading this.

**Comment by vasile-gh** [comment]
did you check and confirm that the cable does nothing when the camera is in video mode?

**Comment by teleV2** [comment]
Works nothing. The cabled shutter works just the same as the one on my NX1. Pushing the cabled shutter makes nx1 escape from the video mode.
By the way, maybe the above suggestion no.1 is not likely because the pin 1 is used for power.
Therefore, suggestion no.3 seems the most likely solution and it will be happy if I can choose 'switching button functions' whenever I want by selecting from the menu or by a combined key press(preferred). I saw on a post that some Nikon have that kind of menu.

**Comment by BopBill** [comment]
If understood correctly this is also something I am hoping too to happen:

3.Or switch the function of the 'shutter button' and 'video record button' and 'half-press shutter' for 'ok button' in the system.

I would be happy if only the current video pause/resume button "ok" could instead be the "shutter half press" button. That would make it possible to make quick short movies without shakiness between clips. Current "ok" button is not good at all for pause/resume use.

**Comment by ottokiksmaler** [comment]
What cameras do you have? I think I'll be able to do it for nx500 but I don't have nx1 and they differ in the way they handle keyboards.

**Comment by BopBill** [comment]
I have NX1.

**Comment by ottokiksmaler** [comment]
For those with NX500:

Run this file https://github.com/ottokiksmaler/nx500_nx1_modding/blob/dev/shutter_to_rec?raw=true

How to run, here is documentation:
https://github.com/ottokiksmaler/nx500_nx1_modding/issues/54#issuecomment-227092096

Testers wanted.

**Comment by Tommixoft** [comment]
@ottokiksmaler  some info wold be appreciated :) created app and who knows what it does and how to use :)
it makes shutter button work as a record button? so how to take photos? or i have to be in movie preview mode it to work?

**Comment by ottokiksmaler** [comment]
Then it's not for you. This is an early release meant for people willing to test. We need to test things before we package them and roll them in mod pack. 
While this program is active shutter button (and USB) will act as rec button. Normal photos are not available. When you exit it (or power off-on) it reverts back to normal operation.

**Comment by Tommixoft** [comment]
@ottokiksmaler  can you know programmatically that you are in movie preview mode? Also can you intercept key event? so your app gets it and others who listens to this even-dont?

SO there could be mod -Enable shutter as rec. So if in movie mode + mod enabled your keyscan starters recording on shutter press. But i guess it's impossible because you would done that long ago :)

**Comment by ottokiksmaler** [comment]
No. The idea is to have it survive power off and on, going to sleep, etc, which can be accomplished by making it a checkbox in mod_gui. Why? Because if your camera goes out of video preview you have to put it in video preview again and if the camera is at 6m high pole or on a drone it gets tricky.
This is a specialist mod, you don't need it often, but when you do need it, you really really need it.

**Comment by BopBill** [comment]
Just want to clarify my sayings.
When I start recording video directly or from standby mode using video record button to start/stop, it makes a video clip. Ok, this is simple and clear.

But if push "ok" button during recording, the NX1 pauses. And if I press again "ok" button it continues recording to the same clip. So no matter how many times I pause, I get only one video clip, no many! Every clip is connected together as one clip.

Problem is that the "ok" buttons position for using it is not good. Difficult to use without shaking the camera. If "half-shutter press" could be used as pause/resume button, it would be much much better.

**Comment by ottokiksmaler** [comment]
There seem to be two different things asked here - use of half shutter as PAUSE button (doable) and full shutter as REC (also doable). The thing is they cannot both be active at the same time (no way to press just full shutter without half shutter).

**Comment by ottokiksmaler** [comment]
@tommixoft it's not impossible, I'm working on something that will enable it for those who want it.

**Comment by Tommixoft** [comment]
@BopBill and @ottokiksmaler  - Bop but shutter button is bad too :D I'm using glidecam and im right handed, so my right hand is always holding glidecam, and thsis tupid camera's rec button is in the ass. to press it i must like crazy shake video, would be awesome if we could pause video recording by pressing button on screen :) I think Otto did that, yes?

**Comment by teleV2** [comment]
@ottokiksmaler
I am really excited now hearing this news! Huge steps foward! very good job!
If you have to choose only one function to the shutter button, I think the shutter should be the "ok" button, not "rec" button. @Bopbill will agree with me because we can push rec button only at the begining and at the end. Whenever video recording is paused by clicking ok button, we can even stop and save it by rec button so you wont have a shaky footage with this trick at the end of the recording at least.

@Tommixoft
I opened this issue because this lets us be able to use a USB wired remote release. The release has only two functions: half-shutter & shutter. you can grab it with your left hand.

**Comment by teleV2** [comment]
Or, we can make a remote release so that we can press just full-shutter without half-shutter. I have NX1 and I want to be a tester with pleasure.

**Comment by Tommixoft** [comment]
or we can use Samsung app and forget all of this :D

**Comment by teleV2** [comment]
@Tommixoft hahaha another battery hahaha

**Comment by ottokiksmaler** [comment]
Or you could use fresh off the compiler **onscreen_key** :)

It's here: [onscreen_key] (https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/onscreen_key?raw=true)

Usage:
```
onscreen_key [Label] [button] [x y] [width height]
```

Displays a button at given coordinates (default 400 0) of given size (default 120 60) with given label (default REC) and clicks given button (default rec)

**To dismiss** - long-click it for at least five seconds.

Record - rec, OK - ok, Half-shutter - S1, Full-shutter - S2, Menu - menu, etc.

How to test: [see here] (https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/Testing%20programs%20-%20HOWTO.md)

**Comment by Tommixoft** [comment]
@ottokiksmaler NICE! but 3secs to kill it would be better. 5 tooo long..in that time people die :D

**Comment by teleV2** [comment]
@ottokiksmaler Thank you for the information about  onscreen button. However, I still would want to use wired usb remote release while I am using two-hand type gimbal. Since NX1 is heavy, I am planning on embedding usb release on one hand grip if you made this. Thank you for your all efforts anyway.

**Comment by ottokiksmaler** [comment]
I'm on it, did some tests and don't see any downsides to having half press as OK (pause) and full press as REC. 

Now, so we want to trigger this behaviour from menu or by some key shortcut (like EV+MOBILE)? I'm trying to keep Vasile's hack clean, so I'm looking for an appropriate solution. Triggering from menu would also survive power off and sleep.

**Comment by Tommixoft** [comment]
@ottokiksmaler  from menu. So everything would be more like Magic Lantern. And Vasile's mod great because of showing current status... Maybe its your job dont know.. anyways i vote for Menu stuff, not keys.

**Comment by teleV2** [comment]
whichever is ok for me except that I have NX1 so I am not able to test unfortunately.

**Comment by BopBill** [comment]
@ottokiksmaler I don't know if this is for NX1 too, but as long as mod could be used with screen or EVF it is same for me how to trigger mod on.

**Comment by ottokiksmaler** [comment]
I don't have access to NX1  so I'll have to find a way...

**Comment by vasile-gh** [comment]
@ottokiksmaler "I'm trying to keep Vasile's hack clean" - why? dirty it up as you wish :-)

**Comment by ottokiksmaler** [comment]
@vasile-gh will do when we make it work reliably - I see your pack as "stable" version, not to be messed up without good reason :)

**Comment by Tommixoft** [comment]
@vasile-gh  it's already dirty :)

**Comment by ottokiksmaler** [comment]
OK, here is the version that should work on NX1 as well: https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/shutter_to_rec?raw=true

Now, changes are (due to specific ways NX1 handles keys and me being unable to expriment directly):
 - Keys activate on **release** - so click is still a click, but nothing happens if you press the shutter and don't release it
 - You have 1s to release half-press after clicking full-press shutter or the camera will interpret that ac another click on OK 

This sounds complicated but it's not - just click the buttons - don't hold them pressed for long time and you will be fine.

NX1 testers wanted :)

**Comment by teleV2** [comment]
I tried to follow [https://github.com/ottokiksmaler/nx500_nx1_modding/issues/54#issuecomment-227092096](url) but stuck with 

> 5. start Vasile's GUI and select "telnet" from the menu

I guess I need to install Vasile's GUI first, right? Then, what is Vasile's GUI and how to install it?
Please understand that I am very new here.

**Comment by ottokiksmaler** [comment]
Sorry for that, you need to install this 
https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/nx-on-wake
And then this 
https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/video-bitrate-mods/nx-patch

**Comment by teleV2** [comment]
It works great!
It works great with USB wired remote release as well!

Did you take into account that we can stop recording by clicking rec button while the recording is being paused? I tried it and the result was good but I am just wondering.

Thank you very much. So, I have to wait for the next version of nx-patch including this, right?

**Comment by ottokiksmaler** [comment]
That's the reason for 1s release time (or if would trigger OK again). I guess @vasile-gh could put it in the next version, it was asked for a lot (and it's tiny). Off script should just do killall - SIGINT shutter_to_rec

**Comment by BopBill** [comment]
Great if this works on NX1! I can't test because I don't know anything about Linux or telnet.

**Comment by vasile-gh** [comment]
I will try to push out a beta this weekend, including this and the other @ottokiksmaler mod that is still not included - on mobile now and do not remember what it was doing, sorry.

**Comment by outerbeat** [comment]
@ottokiksmaler I'm also here on github, follow all modding topics almost all the time. Good to see such progress!
