### ISSUE TITLE
log and sdb activation key combos?

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#43]
home/songha.choi/osp/NX500/linux-3.5/arch/arm/mach-drime5/nx500/dev-keys.c
```
/**
 * NX500 LOG KEY Configuration
 */
static struct d5_keys_keycode drime5_log_keycode[] = {
        {2, KEY_KP8}, // up
        {3, KEY_REFRESH}, // EV
};

/**
 * NX500 SDB KEY Configuration
 */
static struct d5_keys_keycode drime5_sdb_keycode[] = {
        {2, KEY_KP2},   // DOWN
        {3, KEY_KPDOT}, // DEL
};
```
/home/songha.choi/osp/NX500/linux-3.5/arch/arm/mach-drime5/**nx1**/dev-d5keys_polled_before_merge.c
```
/**
 * NX500 LOG KEY Configuration
 */
static struct d5_keys_keycode drime5_log_keycode[] = {
        {6, KEY_KP2}, // DOWN
        {5, KEY_F18}, // AF-ON
};

/**
 * NX500 SDB KEY Configuration
 */
static struct d5_keys_keycode drime5_sdb_keycode[] = {
        {6, KEY_KP2},   // DOWN
        {5, KEY_KPDOT}, // DEL
};
```
despite the comments it has to be for NX1 because NX500 does not have AF-ON, and it is in an nx1 folder

**Comment by ottokiksmaler** [comment]
Yes, polled is for nx1 (files are organized differently in /sys between the two cameras, nx500 uses d5-keys and nx1 uses polled suffix - see the S1 masking mod for exact filenames and bit values)
