### ISSUE TITLE
EV held launches mod interface and it remains locked.

### ISSUE THREAD

**Issue by arspr** [ottokiksmaler/nx500_nx1_modding#45]
If I hold EV, (not double tap but just hold) I go to the mod menu and remains "locked".
Problems with it:
+ The EV remains locked. I mean I can press OK to go out of the mod menu but as example in M my back dial continues doing EV when I have (Shutter + Apperture)...
+ The mod menu sometimes continue appearing without further intervention by me, or it appears with a single EV press.
+ I cannot launch DEV menu. (I suppose I cannot do the EV-hold + OK + EV-release part quickly enough before the mod menu is launched in the EV-hold).

I'm on NX1 + 4.12

**Comment by arspr** [comment]
Another issue I suppose you know while the mod menu is displayed you cannot:
+ Turn the camera off.
+ Change PASM mode.

**Comment by ottokiksmaler** [comment]
I should probably quit mod_gui on any key outside of EV and OK. Vasile?

**Comment by vasile-gh** [comment]
what mod are you on? KS or vasile and what version?

**Comment by vasile-gh** [comment]
I was going to suggest that, Otto.

**Comment by vasile-gh** [comment]
and make sure that EV EV <> EV kept pressed for more than 1 second

**Comment by ottokiksmaler** [comment]
This EV thing is related to only NX1 - no such problems on NX500 - we'll get it sorted as you have NX1 (I need output of keyscan in debug mode when double clicking EV and long pressing EV on NX1 to see what's going on).

**Comment by vasile-gh** [comment]
ok so what do I need to do for the debug output?

**Comment by vasile-gh** [comment]
Scripts:        Configuration file:main
Configuration file: main.NX1
Model: NX1
Release: 1.41
Running MOD_GUI
CONFIG: Resolutions     /opt/usr/scripts/mod_gui /tmp/resolutions
CONFIG:         (null)
CONFIG: Bit Rates       /opt/usr/scripts/mod_gui /tmp/bitrates
CONFIG:         (null)
CONFIG: Make Default    /bin/cp /tmp/initial_patches.sh /opt/usr/scripts/
CONFIG:         (null)
CONFIG: About v4.12     /opt/usr/scripts/about.sh
CONFIG: Uninstall       /opt/usr/scripts/uninstall.sh
Debug ON
Key: XF86WWW
Key: XF86WWW
Key: XF86WWW
Key: XF86WWW
Key: XF86WWW
Exiting the app.

no difference between long press EV and short press EV.
double click  triggers the key twice Key: XF86WWW, long click just generates one event.

**Comment by ottokiksmaler** [comment]
I need output from keyscan, just add debug as the last parameter and start it from telnet.

**Comment by vasile-gh** [comment]
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/mnt/mmc/scripts//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150

looks like EV also generates EV+EV

**Comment by vasile-gh** [comment]
no difference between short and long presses :-(

**Comment by vasile-gh** [comment]
ok i ddi some more experiments and it looks like the keyscan does not measure properly the 1 sec - it always thinks there was less time that passed.
After the first time I do EV EV, each EV press will always bring up the mod menu.

**Comment by ottokiksmaler** [comment]
I don't get it, what version of keyscan are you using? There is explicit 
			if (NXKEY_EV1 != (int)ev.code && msec_elapsed < 1000 && ev.code == previous_ev.code && ev.value == previous_ev.value) {
In the code - double click of ev on nx1 should not work at all.

**Comment by vasile-gh** [comment]
file size is 603448 and it is the latest from the Master branch

**Comment by ottokiksmaler** [comment]
Not at computer right now, will have to check, binary might be old.

**Comment by ottokiksmaler** [comment]
Uploaded new version, it's dynamically linked (much smaller). Also, EV_EV does not work on NX1. I suggest using EV_S1 or EV_AFON as replacement. Or we could test this further? I have uploaded versions for test on NX1 in dev branch.

**Comment by vasile-gh** [comment]
ok I bricked my own NX500 so cannot do anything right now.
:-(

**Comment by vasile-gh** [comment]
!@#^&%*&^%@#*!^#%@*$

**Comment by ottokiksmaler** [comment]
What happened?

**Comment by vasile-gh** [comment]
I know what I did wrong but nothing I can do now - I simply forgot to add a & to a systemd unit file
I put ExecStart=/usr/opt/scripts/nx-on-wake  but I forgot the & at the end

**Comment by vasile-gh** [comment]
want to switch to google talk or do we continue here

**Comment by ottokiksmaler** [comment]
Before di-camera-app starts?

**Comment by vasile-gh** [comment]
well, it is a unit that was linked into multi-user.target.wants

**Comment by vasile-gh** [comment]
which I believe is before di-camera-app

**Comment by vasile-gh** [comment]
FUCK

**Comment by vasile-gh** [comment]
I am tired of this shit. I had an epiphany this evening about why we cannot properly update the hibernation image, and tested it and I was right. Basically the hibernation image is updated straight after the battery is inserted back, and the camera restarts again before you can get access again to it

**Comment by vasile-gh** [comment]
so the key is to create a service - I used the xscim.service as a template because it is on while the cam is on, and created a duplicate w/another name but set up the same way

**Comment by vasile-gh** [comment]
and I created a very small program that basically does only the suspend check from your keyscan, and runs a program if it detects wakeup. Called it nx-on-wakeup.
and put it in the service

**Comment by vasile-gh** [comment]
you still here?

**Comment by Tommixoft** [comment]
I think you just should stop making mods. You made bitrate mod and so on, leave it. NO point in making it better if it takes year, nx system is getting old. Also samsung quality as always super bad and it breaks soon.

**Comment by arspr** [comment]
@Tommixoft:

What a useful and encouraging post!!! With people like you I just cannot understand how manhood has not reached Mars twenty years ago...

Now seriously: I do really hope you don't work in a bank deciding if entrepreneur's projects can be given credit or not...

**Comment by vasile-gh** [comment]
@arspr sorry, you will have to wait a bit before I can be of help - I'd like to have the burner camera back before I do any more hacking. Hope you understand my situation.

**Comment by Tommixoft** [comment]
@arspr   :DDD i work as a developer. I just feel sorry for Vasile, Otto spending time, money... and getting briks and so on... I just want good for them. We already have birtate mod and 2.5 there will be no 10bit mod..well we can live with that :)

**Comment by arspr** [comment]
Sure, vasile. Take all the time you need (returning BOTH cameras or whatever) before you release anything. More over before playing with hibernation... I, too, wouldn't play with my NX1...

I only hope this bug about EV keys can be solved sooner (by Otto k?) as it's really killing the GUI usage of your mod. A 4.13 version would be really healthy. But again, no problem if we have to wait even for that.

Right now, the most important thing is you recovering your cameras (and the confidence in case it's not as high as it should be).

**Comment by vasile-gh** [comment]
I will quietly post a test version just for you, using the new version of
keyscan from Otto, and with a different key combination for the NX1 - looks
like NX1 does not support EV_EV for some reason.

**Comment by vasile-gh** [comment]
@arspr what key combo would you prefer to launch the user interface on the NX1?

**Comment by ottokiksmaler** [comment]
Is EV+AFON doable?

**Comment by vasile-gh** [comment]
We'll only know when we try it. Let me quickly put together a package

**Comment by ottokiksmaler** [comment]
I mean ergonomics wise, on nx500 I prefer ev s1 but it's hard on nx1

**Comment by vasile-gh** [comment]
there you go - give it a try.
[here](https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/video-bitrate-mods/nx-patch)

**Comment by vasile-gh** [comment]
@ottokiksmaler nope EV key always sends double click on EV - tried it on my NX1. Basically you cannot do single click, keyscan will always report double.
I wonder if it is not related to the BBAF.
Anyway, I find OK OK much more logical and reasonable.

**Comment by vasile-gh** [comment]
It would not be difficult to configure it upon install to use different
keys on NX1 and NX500.
What would you prefer on NX500? EV_S1 ?

**Comment by ottokiksmaler** [comment]
Shouldn't the click on various keys while ev is pressed just work, even on nx1?

**Comment by ottokiksmaler** [comment]
It's same to me, I like EV_S1 but people seem to prefer ev_ev,  either way it's trivial for me to change... So maybe better ask on dpr/eos?

**Comment by arspr** [comment]
Hi, guys I'm bedridden with flu (yes, I know, in JUNE, and weekend, WTF!!!), so not much testing...

Nevertheless I'd propose EV+Menu. I mean if Menu brings the stock one, it really feels natural a "shifted" Menu brings the mod one

**Comment by ottokiksmaler** [comment]
Ev+menu does not work. Sorry

**Comment by arspr** [comment]
Then I think the better one is NX-KS one: EV+OK

(Unless there's a nasty reason for not using it, which I'll fully understand...)

**Comment by ottokiksmaler** [comment]
Here is an easy test - without mods - if a ev + some key does nothing (like ev+ok/up/down/...) it can be used. If it still does something (like ev+menu/rec/...) we cannot use it. Ev+ok is usable. For example, the reason I prefer ev+halfshutter is that I can do it with one hand on nx500 (ev is on the back where afon is on nx1). Same thing with double-click of ev. 
If keyscan is used, we could probably make an install time choice what key combination to use for mod gui. Vasile?

**Comment by vasile-gh** [comment]
yes we can make it a choice - even a post-install choice.
But I am not touching my NX1 - cannot afford to risk the camera and in any
case do not want to mess with it with experimental things, except after
NX500 tests are complete - so will wait for the return of at least one of
the NX500.

But I like your idea of half-shutter + EV on NX500.

**Comment by arspr** [comment]
From my bed: ;-)

@ottokiksmaler, I've just uninstalled the patch, and EV+Menu does nothing (at least nothing I can notice)... ?!?!?!??

OTOH I really think the "speed" in mod GUI accessibility should not be an important decision factor. You'll seldom use it and never in a critical shooting situation. Having said this, you can actually choose whichever combination you like.

But, I really don't like EV+HalfShutter as it doesn't feel "right". I mean, HalfShutter accessing a menu? It isn't just user-friendly at all.

But, as I've said, a really unimportant decision. Use whichever key combination you want or it's easier to code.

**Comment by ottokiksmaler** [comment]
That's on nx1, right? I'll have to recheck on nx500 with new firmware too. 
Ok, this is what I will do : make mod_gui aware of "pages" of options so we don't need to restart it again and again and allow for color coding the buttons. Will also make possible to change the key that invokes the mod.

**Comment by vasile-gh** [comment]
not sure what you mean by <aware of "pages">
to change the key you can make a menu page that will simply trigger a rename of the shell file.
Can you check my nx-patch to see what I did with the mod_gui - I am loading the page defs from /tmp in order to make them show the current values.

**Comment by arspr** [comment]
@ottokiksmaler: Yes, on NX1 with FW 1.41. EV press displays the EV compensation icon on the screen. Then Menu press (while EV is held) does not do anything.

**Comment by ottokiksmaler** [comment]
I meant that when you want to show sub menu got actually launch another instance of mod_gui. I want to avoid that

**Comment by vasile-gh** [comment]
yeah this causes a lot of issues indeed. If you could build nested menus it
would be great.

But I know it is not easy

**Comment by arspr** [comment]
I think you can close this...

Buuut, the (offtopic) issues I wrote on my second post. When the menu is displayed, PASM dial doesn't work and you cannot turn off the camera...

**Comment by ottokiksmaler** [comment]
It's on topic - I hav ejust uploaded a new version that exits on any other bey but EV and OK (needed for screenshots for documentation).
