### ISSUE TITLE
Feature request: delayed record start

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#47]
May sound stupid, but i use stabilizer, and this camera record button is in the ass... is there possibility to make mod so when i press rec button actual recording starts after some delay? :) Now video shakes while im re'hold stabilizer after i pressed rec. i can cut it in post but...maybe mod could be done? :)

**Comment by ottokiksmaler** [comment]
Just make a file named EV_OK.sh (or similar) in your keyscan directory (depends on the mod pack you are using) with following contents 
sleep 3
st key click rec
And make it executable (chmod +x pathToFile)  of on internal storage (/opt/whatever) 
That's it.

**Comment by Tommixoft** [comment]
so EV_OK is the rec button "code" ? Interesting :)
So this also prevents from stoping recording 3 secs too, yes?
thanks

**Comment by ottokiksmaler** [comment]
No, EV_OK means "execute this when the user presses OK while holding down EV button". Rec name is "rec" from "st key click rec". What this will do is: when you press together EV and OK it will wait for 3s and then emulate click on "rec" button. If you press "rec" it behaves as it normally does.

**Comment by Tommixoft** [comment]
to press EV+OK need to have 2 hands which is not very ok when you holding stabilizer.  But i do understood your suggestion, to just map other key to do the job. Thanks!
