### ISSUE TITLE
is it worth to update to 1.12?

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#48]
Hello Otto Vasile, sorry stupid topic, but maybe others have the same question as me. Im not upgradig my camera because of afraid of hidden shit samsung may put there. 
Now i see Vasile makes his bitrate mod and looks like it's for 1.12 only. SO i guess if you guys upgreded than i can too. But is there ANY advantage of new Fw except from useless android fix.

SO far im not happy with nx500, color grading is just impossible, codec sucks. Minimal corections make many artifacts.

**Comment by vasile-gh** [comment]
Well, this is for you to decide. Me, I made my decision :-)

I do not think they did anything "hidden" beyond the DEV access - for which
they had good reasons.

rgds

**Comment by Tommixoft** [comment]
updated :) thanks if you say it doesn't contain trojans -i believe :D Now will go and brick camera trying to install your newest method of loading scripts :DD Funny thing-i dont even use any scripts but i must have mods just to have :D

**Comment by ottokiksmaler** [comment]
You can always build it from source so you are extra extra sure...

**Comment by ottokiksmaler** [comment]
BTW, increase the bitrate to 160Mbps+ and you will have zero artifacts in your video. It's like magic.

**Comment by Tommixoft** [comment]
@ottokiksmaler  i hate linux complexity so i rather stay away from compiling. 160- too much for me... i don't see reasons to use such bitrates, unless of course in post than use lower bitrates for final product. Will try higher bitrates..cause so far it just sad too look at video in adobe premiere even slight adjustment makes some colors break.

**Comment by ottokiksmaler** [comment]
You're kidding, right? You either have super low bitrates for nice quality in 4k or you can have higher, but still lower than other cameras, when you want to do more adjustments in post. For reference, panasonic uses 200 and canon is at over 300 for at best same quality and nobody complains...

**Comment by ottokiksmaler** [comment]
BTW, people complain about h265 support in premiere, they seem much happier with other products, should be worth while to see what settings people are using for adobe.

**Comment by Tommixoft** [comment]
@ottokiksmaler  no im not kidding. Im not filmmaker who have 256GB cards and can film hours of crap and then delete when i get back to pc. I try to save space on card. if i on vacation 2 weeks and i do not have pc, i must save card space to get whole holydays :) h.265 is really not that great as they want us to think. In every comparison people show that it's like 3 times more efficient..but it's bullshit. i can more easily edit 12Mb/s h.264 than 70Mb/s h.265.  Will try other products...maybe really adobe fucks it.
