### ISSUE TITLE
silent shutter NX500 - touchscreen doesn't work

### ISSUE THREAD

**Issue by maxwawa** [ottokiksmaler/nx500_nx1_modding#5]
Hi,
We appreciate and thank you for your work on the NX500.

I remade your telnet skript on ST commands and recorded this on SD card NX500 and silent shutter work great :) but touchscreen doesn't work.
Please help what you need to do to operate a touch screen too with the same time.

I wrote this
https://drive.google.com/file/d/0B7Dv1h3r4-u6MXhuQ1JmYnlTdjQ/view

Greetings.

**Comment by Tommixoft** [comment]
what if you just write this in nx_cs.adj file:

st cap capdtm getusr 117
st cap capdtm setusr 117 0x00750001
st cap capdtm getusr 117
sleep 1
killall dfmsd

**Comment by ottokiksmaler** [comment]
It doesn't work that way. Adj file is used only to start she'll script for (test.sh). You can put st commands in script file. 
Regarding touchscreen, it would work but not all options are working. So you see series of green dots on the left side? If yes, that means that dfmsd is still running (touchscreen does not work whole it runs) and you need to kill it (msybe add another 
sleep 3; killall dfmsd
 at the end on test.sh?)

**Comment by maxwawa** [comment]
Thank you for all answers.
Yes I still seeing green dots on the left side.
What do you mean  "You can put st commands in script file" ? 
delete all three files?

**Comment by ottokiksmaler** [comment]
No. info.tg is just there to point camera to adj file that is there only to tell the dmfsd to start the script (called test.sh in my version and killdfmsd.sh in this other version). In that script file there should be something like 
sleep 3
killall dfmsd
At the end. Sleep 1 will not work reliably as 1 second is quite short time, 2 seconds are better, 3 should be plenty.

**Comment by maxwawa** [comment]
thanks ottokiksmaler but still doesn't work (I can still see the green dots)

**Comment by maxwawa** [comment]
...and touchscreen is still inaccessible

**Comment by Tommixoft** [comment]
do you have access to camera via telnet? you may try to run killall command via telnet and see what happens. Do you use newest firmware? maybe in older something different.

**Comment by ottokiksmaler** [comment]
Try with my sd.zip file here and just add st sequence of commands to the end of test.sh file

**Comment by maxwawa** [comment]
Tommixoft by the tlenet this is problematic and after reebot silent shutter is gone.

ottokiksmaler i still don't kill the dfmsd process
I placed  on SD card this
https://drive.google.com/file/d/0B7Dv1h3r4-u6RDhuWllsaHB6bm8/view?usp=sharing

**Comment by maxwawa** [comment]
Enable-1080p-120fps-video-on-NX500
https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/Enable-1080p-120fps-video-on-NX500.md

This above script has the same effect - touchscreen doesn't work

**Comment by maxwawa** [comment]
I have just checked telenet session and by telenet st comands silent shutrte and touch sreen are work perfectly :) so by the script it is possible. just as?

**Comment by maxwawa** [comment]
in telenet session i wrote:
[root@drime5 ~]£ st cap capdtm getusr 117
UserData is ADJUSTSHUTTERTYPE_MECHA (0x750000)
[root@drime5 ~]£ st cap capdtm setusr 117 0x00750001
UserData is set
[root@drime5 ~]£ st cap capdtm getusr 117
UserData is ADJUSTSHUTTERTYPE_ROLLING (0x750001)

end of line i wrote only  "killall dfmsd" and finally touchscreen started to work

**Comment by ottokiksmaler** [comment]
I don't know why it would not work, it's exactly the same thing. Maybe inserting sleep 3 at the beginning and before killall could work.

**Comment by maxwawa** [comment]
"Maybe inserting sleep 3 at the beginning and before killall could work"

touchscreen still doesn't work

**Comment by Tommixoft** [comment]
i think your SH file is just not being executed. Maybe otto knows some other commands you could write to test is your sh executed or no. maybe there is some linux command to create text file inside card. if it will be created than file commands is executed if not-no :D

**Comment by ottokiksmaler** [comment]
Put 
date >> /mnt/mmc/itworks.txt
sync; sync; sync

In the script file and see if the file is there

**Comment by maxwawa** [comment]
I placed 
date >> /mnt/mmc/itworks.txt
sync; sync; sync 
in test.sh and/or  nx_cs.adj
but still to no avail.

no matter where you put the command but I get the impression that are performed only comment this prefix "st cap etc." others are ignored.

Even putting all the commands in the nx_cs.adj has the same effect.

**Comment by maxwawa** [comment]
I tried all night and analyzed, and finally everything it works great :)))))
Silent Shutter and touchsscreen WORKS together ! but ...

It turned out that it is very important parameter of "sleep" in the killdfmsd.sh
"sleep' have to set on "2" or "3" it is close to success but unfortunately NX500 does not always work stably

**Comment by ottokiksmaler** [comment]
Yes, that's why I told you to use leather number 
> Sleep 1 will not work reliably as 1 second is quite short time, 2 seconds are better, 3 should be plenty.
Glad to hear is working now

**Comment by ottokiksmaler** [comment]
I just love auto correct... 
Yes, that's why I told you to use larger  number 
> Sleep 1 will not work reliably as 1 second is quite short time, 2 seconds are better, 3 should be plenty.

Glad to hear is working now

**Comment by maxwawa** [comment]
ottokiksmaler you have right about killall dfmsd beacuse after that command  not all options are working ex. chosen AF point on LCD or mechanical shutter don't work.
so generally this script working but it needs improvement.

**Comment by ottokiksmaler** [comment]
Actually, I need to find a way to run it without info.tg file (straight from camera without entering factory mode as we do now). I'm working on it.
