### ISSUE TITLE
Nx-patch mod not saving values(?)

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#50]
Hi Vasille...just installed your mod... but looks like it doesn't save anything.

I set bitrates, then reboot camera i go to GUI (EV+EV) and i see it shows default values, so i make video and i see that indeed it's default values. Resolution too resets. i set HD and VGA to be 2.5k and now they gone.  I only turned off camera.
Also i never get success message don't know does it have to be or not, but when i enter bitrate and press "confirm" it just closes.

**Comment by vasile-gh** [comment]
did you press "set as default"?

I need to make the README more explicit - they are actually not saved
unless you set them as default. the reason is because I am trying to keep
writes to camera flash to a minimum to avoid any issues.

Please let me know

**Comment by Tommixoft** [comment]
Yes sorry... as always i dont read instructions and try to do whats logic. Yes it saved now.
So when i set as default it wont write camera flash, only once, then only ram will be effected and ram is made for being written many times so wont hurt...yes? :)

**Comment by Tommixoft** [comment]
PS your problem with instructions is -you try too hard to explain. I would write your On wake instruction in 3 sentences. you wrote whole book :) it juts makes harder to install that mod safly because you need to read bunch of words and also work at the same time :)

**Comment by Tommixoft** [comment]
My instruction version for On Wake:

1. Copy zip content to the root of your sd card.
2. Turn on your camera, you will be asked to enter number. Enter xxxxxxx and press confirm.
3. Wait 5 mins.
4. Take your battery off, without touching any buttons.
5. Wait 10 sec. and reinsert battery.
6. Wait another 4mins and then restart camera and happy using.

**Comment by vasile-gh** [comment]
well... OK - too late though, and by the way I like scaring off people :-)
