### ISSUE TITLE
Enable user downloadable applications 

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#52]
We should enable end users to install standalone applications in a simple way. 

This would include 
  -  place to host the apps - I suggest github at least for now 
  - standardized format of distribution
  - standardized method of deployment to camera 
  - gui to browse the available applications 
  - method to update installed applications 
  - gui for installed application chooser (launcher) 

Now, we could either go the simple route and use zip files for apps that are unpacked to predefined path on camera or SD card, they are scanned by future version of mod_gui or similar and users can launch them from there (possibly assign a key shortcut). This would also involve some sort of multi page list as it's pushing it already over 12 items (but do we need over 12 apps?) or a setting to put app in one of the 12 slots. 

We could use apt or similar but I doubt there is any need for that. We might agree on some common set of utilities expected to be on the camera (popup tools mostly), but apps should be self contained. 

If you feel uncomfortable with this approach, other thing that comes to mind is a method to deploy changes from SD card (that is configured by some gui tool running on pc). 

Thoughts?

**Comment by Tommixoft** [comment]
if need help with hosting and website - i can help.

**Comment by ottokiksmaler** [comment]
Agree - simple is better. 

Regarding apps, they would not be assigned shortcuts, that would be a special case and we should aim for a single process that interprets events, this is for standalone apps (like what you said) and it's perfectly ok to launch them from menu (they are not spur of the moment type things that you activate every few seconds). This solves issues with competing for events, etc. 

Will have to think about it tomorrow a bit more.

**Comment by Tommixoft** [comment]
What if 90% of apps could be activated only via GUI? so only most important will get keys. I mean who needs focus staking on a physical key? and so on. In fact there is so little thing that need physical key... all is needed is to reprogram developers not to use keys, but use gui menu.  Phones doesn't have keys but so many applications :)

**Comment by ottokiksmaler** [comment]
Uploaded new version of mod_gui with support for standalone apps https://github.com/ottokiksmaler/nx500_nx1_modding/commit/fc49412fe14da0a369dbfc23c9800006b406f9bf
