### ISSUE TITLE
Crop registers

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#53]
DOnt know do you familiar with KinoSeed post

> From @NXKS2
> 
> Removing crop-factor and custom resolutions on NX500.
> ... it appears that we can control the crop factor (remove it) and even have custom resolutions, by controlling the EP_Resize registers. As you can see for NX500 all non-crop simply have the same value for the scanning and output (ex VGA), where the crop modes have one scanning resolution and another for the output (ex DC). For removing the crop, we don't even need to recalculate values, just repeat the input to output value. However setting those is a bit trickier than expected....
> 
> 4K DC
> [20826000] 0140000E 10000000 0438000C 08700000
> 
> VGA
> [20826000] 05000000 05000000 03C00000 03C00000

Would be great if you could look at it. Sorry if you already know...

**Comment by ottokiksmaler** [comment]
I'm already working on a tool for that, but with little success as of now.

**Comment by Tommixoft** [comment]
@ottokiksmaler  but what the crop means? so if crop will be removed doesn't it mean that sensor will get 6k data instead of 4k?

**Comment by ottokiksmaler** [comment]
No, camera actually sends two resolutions - source and output, source is 4k on nx500 and 6.5k on nx1, output is the same 4k for both. In *theory* you could get 28MP video but I doubt the camera has enough processing power.

**Comment by Tommixoft** [comment]
well if you find how to change those registers than we could see :D i think nx500 not so less powerful in terms of cpu. NX1 video is much better quality than nx500 and it's because of 6k of course, would be awesome to get at least 5mins [to protect of overheating and so on) 6k->4k video.

**Comment by boomyjee** [comment]
can you pls share your progress, i do have nx500 and some programming skills and i wish to try?

**Comment by Tommixoft** [comment]
@boomyjee  i think here more needed debugging skills then programming :)
