### ISSUE TITLE
Standalone apps - directory and file structure

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#55]
Proposal (mostly for @vasile-gh to check-off what is OK for his mod pack):

- [x] Assign EV+MOBILE to start app launcher interface - can be done independently of mod pack
- ~~Assign one slot in GUI for mod pack to start app launcher - should have support in mod pack~~
- [x] Apps to be installed in separate directory for every app
- [x] Base directory to be ```/opt/usr/apps/``` - so for app named ```demo``` it should be ```/opt/usr/apps/demo```
- [x] Every app contains file named ```app.cfg``` with following contents:
  - [x] First line - Full name of application, for example ```Demo application```
  - [x] Second line - version number of application, in major.minor format, for example ```1.0```
  - [x] Third line - Command to be executed to run application relative to installation directory, for example ```demo.sh "First param" second 4 true &``` would be expanded to ```/opt/usr/apps/demo/demo.sh "First param" second 4 true &```
  - [ ] Fourth line - optional - documentation with rudimentary HTML format (depends on support from EFL toolkit) or URL to be opened in browser with more detailed documentation (if it starts with http:// or https://)
  - [ ] Fifth line - optional - URL for current version of app - would have to be defined better
- [x] So, given example wuould be equivalent to having a line in mod_gui config file containing
```button|Demo application|/opt/usr/apps/demo/demo.sh "First param" second 4 true &```

**Comment by vasile-gh** [comment]
well, for me I am not sure how the mod pack will evolve because I am still thinking on the future architecture - this is why I am implementing (temporarily) silent shutter and focus stack using what is available right now.
I therefore selected the options that leave me max liberty and hopefully could be reused to the max in the future :-)

**Comment by ottokiksmaler** [comment]
Uploaded new version

https://github.com/ottokiksmaler/nx500_nx1_modding/commit/fc49412fe14da0a369dbfc23c9800006b406f9bf
