### ISSUE TITLE
EV always generates double event

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#56]
@ottokiksmaler any idea why I ALWAYS get EV_EV whenever I press EV?
Here's an example debug output: S1 **double** click followed by EV **single** click
```
PRESSED  125
RELEASED 125
PRESSED  125
Doubleclick S1 125
No such file '/opt/usr/nx-on-wake//S1_S1.sh' or '/opt/usr/devel/scripts//S1_S1.sh'
RELEASED 125

PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/opt/usr/nx-on-wake//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
```
I am getting requests to map the menu key on NX1 to EV+OK and on my NX1 it never works. What should I do - release as EV_OK although it most certainly does not work on my camera?

**Comment by ottokiksmaler** [comment]
Can you try it with keyscan binary uploaded yesterday?

**Comment by ottokiksmaler** [comment]
And this one https://github.com/ottokiksmaler/nx500_nx1_modding/commit/648dc2f15ba22aa6a7b89adee218e802f660e733#diff-ec98ddbdebf88abb34f8f213b7e5fa71

**Comment by vasile-gh** [comment]
I think so but I am at work so cannot confirm. Will look into it tonight.

**Comment by vasile-gh** [comment]
BTW. I am making progress with di-camera-app shared object injection :-) Looks like I will be able to tap into its internal state.

**Comment by vasile-gh** [comment]
@ottokiksmaler I checked and I am using the latest (uploaded two days ago)
```
(zeus:vasile)-(jobs:0)-(~)
(! 502)-> md5sum ~/nx/scripts/nx-patch-v5.11/nx-on-wake/keyscan 
494bd92c210ac9dd45874d36b3aba774  /home/vasile/nx/scripts/nx-patch-v5.11/nx-on-wake/keyscan
```

**Comment by ottokiksmaler** [comment]
Possible fix for NX1 EV doubleclick here https://github.com/ottokiksmaler/nx500_nx1_modding/commit/ea8b29241b74a6eb0483eff07a5bbda837c88d7f
But needs testing on NX1 (simple idea - don't detect very fast doubleclicks <50ms)

**Comment by vasile-gh** [comment]
nope.
```
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/opt/usr/nx-on-wake//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
PRESSED  150
Combo EV + EV 150 PRESSED 
No such file '/opt/usr/nx-on-wake//EV_EV.sh' or '/opt/usr/devel/scripts//EV_EV.sh'
RELEASED 150
```

**Comment by ottokiksmaler** [comment]
This is crazy... But it's not the worst, for example, SAS mode generates one event for keyscan but two different key clicks for GUI apps... Will have to see later tonight to enable more debugging to see what's going on.

**Comment by ottokiksmaler** [comment]
Hah, it seems there is no cure for stupid, was checking for wrong key code... Try this https://github.com/ottokiksmaler/nx500_nx1_modding/blob/dev/keyscan?raw=true

```
-			if (ev_pressed == 1 && (int)ev.code != NXKEY_EV && (int)ev.code != NXKEY_SHIFT && 1 == (int)ev.value) {
 +			if (ev_pressed == 1 && (int)ev.code != NXKEY_EV && (int)ev.code != NXKEY_EV1 && (int)ev.code != NXKEY_SHIFT && 1 == (int)ev.value) {
```

**Comment by vasile-gh** [comment]
EXCELLENT. works now. Thanks Otto

**Comment by ottokiksmaler** [comment]
BTW, this should also solve the issue with timeout of mod gui reported by @arspr in another issue (as EV resets the sleep timer).

**Comment by vasile-gh** [comment]
@ottokiksmaler yes but I kinda like activating the menu with TOP_LCD_TOP_LCD :-)
