### ISSUE TITLE
xnilo mod install issue

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#60]
xnilo wrote:

        vasile wrote:

            xnilo wrote:

                vasile wrote:

                    xnilo wrote:

                    Hey Vasile,

                    I still have a problem to install the mod on my nx500. I have now tried it for the 5th time. Unfortunately without success in M mode.

                    The firmware 1.12 is virginal installed and all settings are factory settings. Camera is set to M mode. I copied the files to the SD card, install the mod, wait 5 minutes... etc. At the end I see the led blinking 3 times but the user interface does not start.
                    If I switch to AUTO and reboot the cam everything works. But I want to film in M mode.

                    What do I wrong?
                    Is there someone who has the same problem?

                Hi xnilo,

                I answered your previous post on your issue here: http://www.dpreview.com/forums/post/57919050

                And previously I had asked you to:

                    Ok try as I might I cannot reproduce this. Here's what I suggest:

                    1. Re-flash v1.12 and see if the same manipulation triggers the same error with a "virgin" flash. If yes => your cam has a problem. if no, go to 2.

                    2. install nx-on-wake and nothing else. Try the same manipulation again to see if you trigger the same error. If yes, it means there's something going on with my mod although I really cannot see what - but at least I will have a starting point. If no, go to 3.

                    3. install nx-patch v5.02 and retry the manipulation. If no error, you are good. If error, let me know but please write down all steps you took from power on to the error, and also write the state of every setting you can find - so I can emulate it on my nx500.

                Also, you did not report the results of the above tests, if you did do them. As I wrote before, I am unable to reproduce your issue on my NX500, so either you missed some steps in the description of how to trigger it or this is an issue somehow affecting only your camera.

                The objective of the above tests is to narrow down the root cause of the issue, and unless you report the results I cannot really do much to help.

                kind regards

                Vasile

            okay, I did everything you told me...

            1. I reflashed firmware to v1.12... virgin flash. The camera works perfectly. No problems at all.

            2. I installed nx-on-wake and nothing else. During the installation process, the camera was in M mode.
            I have copied the 2 folder "install" and "nx-on-wake" and the file "info.tg" to SD card. I entered the magic number and waited 5 minutes. I took the battery out for 10 sec and then plugged in again. Waited again for 4 minutes. Power off, battery out for 5 sec, battery in, power on. I pay attention to the LED and see that the LED flashes 3 times.
            But the user interface does not start. I see the live view but no user interface. Camera does not respond to any button.
            I switched to AUTO mode and restart the camera (battery out and in). The camera starts perfectly. I see the user interface and everything is as it should be.
            I switched to M mode again and restart the camera. NO user interface.

            3. I did not install nx-patch because the issue was already there with nx-on-wake.

            Is it enough to you that way?
            I installed the nx-on-wake on a virgin flash v1.12. I have not changed any settings of the camera before installing. The issue is only in M mode.

            I hope you can help me somehow.

        OK, I see.

        Looks like there's an issue with the rebuild of the hibernation image - it seems to require that the camera is NOT in M mode whilst you install the nx-on-wake.

        Can you please do the following:

            reflash v1.12
            set your camera in Auto mode
            reinstall nx-on-wake (pay attention to the required power saving settings)
            test again M mode
            report back here.

        Thanks in advance

        Vasile

    okay... again from the beginning.

    1. I reflashed v1.12
    2. I set my camera in AUTO mode
    3. I have reinstalled nx-on-wake (set auto display = off / power save = 30 min)
    --> after installation the user interface has been started (in auto mode everything works)
    4. power off, switch to M mode, power on camera, NO userinface !
    5. start camera in AUTO mode, let the camera turned on, switch to M mode, (no issue), press trash button for video mode, (can not adjust aperture and shutter via adjustment wheels... no reaction), press trash button again, user interface freezes.
    Same issue like installation before.

    Any idea?

Not yet :-(. Again, I cannot reproduce your issue on my NX500.

Can you give me some more information:

    what lens do you have on the camera. Any lens adapters on? Any extension tubes?
    do you have a Samsung battery
    did you disconnect camera from everything as instructed
    did you have any DEV menu items changed (not likely but thought I'd ask.
    did you change any setting after flashing (except power settings and setting camera on Auto)

Thanks

Vasile

**Comment by xnilo** [comment]
Hi Vasile, now I'm here :)

**Comment by NetsurferRus** [comment]
Vasile, hello! Thank you for the development of the patches!
I had the same problem as user xnilo: the freezing of nx500 with nx-on-wake and 5.2-patch and the problem seems to be with the first. The camera behaving capriciously with mode changing. It freezes even with only nx-on-wake (installed succesfully due to blinks),and the pulling of the battery helps only. I attached files that appeared on SD. I hope they will be helpful.
Good wishes!




[nx500_info_files.zip](https://github.com/ottokiksmaler/nx500_nx1_modding/files/324043/nx500_info_files.zip)

**Comment by vasile-gh** [comment]
@xnilo @NetsurferRus I am looking at the logs - xnilo, can you also upload here any .info files from your SD card? thx

**Comment by vasile-gh** [comment]
Anyway, on a preliminary basis it seems like the hibernation image is being incorrectly rebuilt.

**Comment by ottokiksmaler** [comment]
Are you by any chance using non English language on your camera? If yes, could you try with English turned on? I know it sounds silly, but still...

**Comment by vasile-gh** [comment]
Not silly at all - great idea considering it is strlen that causes di-camera-app to crash :-)

**Comment by ottokiksmaler** [comment]
I had some silly issues with utf8 strings in my time and know they are often overlooked by programmers.

**Comment by xnilo** [comment]
Hey vasile, here my log files.
Now I try a test in english language.

[nx500_log_files.zip](https://github.com/ottokiksmaler/nx500_nx1_modding/files/324180/nx500_log_files.zip)

**Comment by vasile-gh** [comment]
@xnilo holy cow - precisely the same crash as @NetsurferRus. looking forward to hearing your results :-)

**Comment by xnilo** [comment]
Hard to believe! But Otto was right. It was because of the language. The install in english language has worked wonderfully. Now it works... yeahhhh
Thanks Otto and Vasile!

**Comment by vasile-gh** [comment]
yes! thanks Otto!

**Comment by vasile-gh** [comment]
OK here comes v1.1 - medium bump coz this is very important!

**Comment by ottokiksmaler** [comment]
No problem, glad we were able to help. Now just to update the instructions... 
Side note, I think that after everything is done you should be able to switch to whatever language you want, it's only the modding that needs to be done in English. Could you test and report back?

**Comment by vasile-gh** [comment]
And another README update - getting tiring to keep changing it :-)

**Comment by vasile-gh** [comment]
But first things first - need to report on dpreview so no-one does it in exotic languages

**Comment by vasile-gh** [comment]
Actually... @xnilo - do you mind reporting it yourself?

**Comment by arspr** [comment]
FWIW. I patched my camera in English (I hate the horrible Spanish translations foreign gear usually have). I've just tested setting language to Spanish and everything seems to work fine. So your theory about language installation and the ability to change it afterwards seems confirmed.

**Comment by vasile-gh** [comment]
OK. changed README (**really** hope it is the last change) and uploaded the new version.
The good news is it is not the mod itself so no one will have to reinstall.

**Comment by xnilo** [comment]
So... I've tested it. After installation I've set language to german and everything worked perfectly.
Great work vasile!!!
I've just installed the nx-patch 5.2 and it seems to work fine too.
Yeah make happy! Now I can film 2.5K in higher bitrate... thats so great!
Thanks alot for your help!!

**Comment by vasile-gh** [comment]
You need to thank Otto for figuring it out.

**Comment by NetsurferRus** [comment]
@vasile-gh, @ottokiksmaler, @xnilo and all, thank you! I used Russian. Will try English later.
