### ISSUE TITLE
nx500 bulb 8 minutes time limit?

### ISSUE THREAD

**Issue by oukene** [ottokiksmaler/nx500_nx1_modding#61]
nx500 bulb limit is 8 minutes..

I wan't more than 8 minutes long explosure..

it is impossible?

**Comment by Tommixoft** [comment]
tell us even 1 reason why need to fry sensor for more than 8mins? 1min is more then enough.

**Comment by vasile-gh** [comment]
astrophotography comes to mind...

**Comment by Tommixoft** [comment]
@vasile-gh :) 8 minutes? :D unless of course he wants to get blurred image (world spins)...then yes.

**Comment by vasile-gh** [comment]
No blur. http://www.astropix.com/HTML/I_ASTROP/MOUNTS.HTM

The sensor is not stressed. the light levels are very low.

**Comment by Tommixoft** [comment]
no blur if photo taken from telescope, i was thinking more like http://i.dailymail.co.uk/i/pix/2013/04/21/article-2312460-19697E41000005DC-228_964x640.jpg

**Comment by oukene** [comment]
Yeah, I'll use astrophotography
nx1 is no limit bulb time, but nx500 is 8min...

**Comment by Tommixoft** [comment]
can i for my personal knowledge see how dark is photo with 8 mins shutter speed? i cant imagen how dark object have to be that 8mins is not enough.

**Comment by ottokiksmaler** [comment]
Easy, take a night sky shot ISO 3200 for 15s.

**Comment by Tommixoft** [comment]
@ottokiksmaler  15secs is 465 seconds less then OP is complaining that is not enough :) And im really want to see what in our galaxy is so dark to need more than 8mins exposure time :)

**Comment by arspr** [comment]
@Tommixoft: You haven't understood ottok. 15s at ISO 3200 is the same as 8 min at ISO 100. Do the math. 

(And I don't know if that exposure is or not enough. And I don't know if intrinsic heating of the sensor is harmful or not).

**Comment by oukene** [comment]
I'm understand 8min enough, but sometimes need over 8minutes for best quality

I think the difference is clearly impossible as possible to
