### ISSUE TITLE
Samsung "wifi" API

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#62]
Does anyone tried to look at samsung api of it's app? 
I mean we could make android app with nice gui, and that way can change stuff and apply settings/mods. 
App should use some http protocol to communicate with camera. i once tried but no success their apk is total shit. you install installer, and where is the real app i could not locate inside apk.

EDIT Looks like Bluetooth would made more sense than wifi, it uses BT not wifi.

**Comment by Tommixoft** [comment]
I see that for image gathering it uses camera's 7679 port.

**Comment by mewlips** [comment]
Hi! I am developing an android remote controller app for nx cameras.
Although it is not related with samsung 'wifi' API.

Visit my github repository.
https://github.com/mewlips/nx-remote-controller-mod

There is a install zip file for nx camera and a android apk file.
The app is only tested on my nx500 and in alpha stage.

**Comment by Tommixoft** [comment]
@mewlips  wow looks like what im talking about! :) I think NX mod could be controlled via mobile app too, not just from camera GUI which is very limited. so camera could have some master app and mobile "talks" with it via http

**Comment by gnoober** [comment]
I'd love an android app with live view, peaking and manual focus. that way the focus puller could work with his or her smartphone on set, even when on a gimbal.

**Comment by Tommixoft** [comment]
There is alread such app.  https://github.com/mewlips/nx-remote-controller-mod

**Comment by gnoober** [comment]
It does not seem to include Manual focus though, does it?

**Comment by ottokiksmaler** [comment]
As answered in another issue, you should open an issue with that app so that the author can add that functionality. He is very fast to respond and had implemented several requests functions already. Manual focus control is also documented so there should be no issue with implementation (apart from the UI design which should be simple and functional).

**Comment by gnoober** [comment]
yes I will, discovered this thread a little later , sorry for doubleposting :)
