### ISSUE TITLE
Screen off/on with a press of a button

### ISSUE THREAD

**Issue by bortek** [ottokiksmaler/nx500_nx1_modding#63]
I am using NX500 for Earial footage/film on my hexacopter (sometimes called a drone by ugly media). There is no need of the screen being turned on while in flight thus saving the battery a lot. Therefore a possibility to turn off/on the screen WHILE recording video or taking shots (with a remote shutter trigger via USB) would be very interesting.

Is it possible to achive this by with a press of a physical button. Like press a button screen goes off, press a button again screen goes on. All that not affecting the camera functionality.

**Comment by ottokiksmaler** [comment]
Yes and no. Screen can be turned off but it gets turned on as soon as something happens (like a shutter release, etc). But, since it's AMOLED screen, power consumption is minimal while the screen is black. I can make you a tool that would turn screen to black until you tap it out similar?

**Comment by Tommixoft** [comment]
I think best would be to disable video preview on screen but leaving all the icons. SO would be easy to leave some custom button on screen when click it video comes back. I know it's possible to disable preview, but not sure is it possible via commands. Im pretty sure i saw somewhere that it's possible.

**Comment by bortek** [comment]
Otto: That could possibly do. But what actially happens when screen is black? Is it turning off the LEDs (thus saving power) or is it the TFT matrix just stops letting the light coming form the LED while LED is on? In any way this might work. In anyway, I would first need to start recording (thus press REC button) AND then make screen black and then launch my copter up in the air. 

Tommixoft: Well thing is I need live preview all the time because I stream it from HDMI out to the little devide that converts it to a Analog signal and goes further to Video transmitter that in turn sends a signal to a receiver on the ground. On the ground I have a monitor where I see what camera sees. If disabling preview on the screen would still allow sending data out to the HDMI port then it could be a solution.

**Comment by Tommixoft** [comment]
@bortek i was talking about preview in LCD. i dont think that HDMI preview can be disabled.

**Comment by bortek** [comment]
Okej. I can test both functions if you can implement :)

**Comment by ottokiksmaler** [comment]
It's AMOLED - every subpixel of the screen is an actual LED so turning them to black really decreases the power consumption. 
You can start the recording after the screen is black as well. 
Also, might be wort reading if you want to start/stop recording remotely (if you have a device that can control the USB): https://github.com/ottokiksmaler/nx500_nx1_modding/issues/42

**Comment by bortek** [comment]
@ottokiksmaler Ok then the solution with turning off the screen sounds good.I will take a look at #42, thanks for a tip :)

**Comment by bortek** [comment]
I have done more tests with the camera and thing is the battery last quite a long time so this is not going to be an issue for drone application. I am closing this issue.
