### ISSUE TITLE
Suggestion: Do not exit mod_gui after value set

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#65]
Can you pls make some changes so that when we set value (bitrate, resolution) MOD_GUI not exits. But returns back. or at least launches itself again. SOo anoying to with very value double press EV and go to manu again and again :)

**Comment by vasile-gh** [comment]
yeah I know but its not as easy as that because I have to always rebuild menus to show current settings and it is not as simple as that,

**Comment by vasile-gh** [comment]
v5.3 beta has this
