### ISSUE TITLE
Disable /dev/log_main

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#66]
Is it possible to disable debug info longing? Would love to have such mod. I know this used for log_watcher app, but im not interested in long videos so i prefer to disable logging for performance increase.

**Comment by vasile-gh** [comment]
not that I am aware of, sorry.

**Comment by Tommixoft** [comment]
Dont be, it's bad developer's problem not yours :) Stupid idiots logging every shit in flash memory, really smart move. What if this file get such permission that no app can write to it? :)

**Comment by ottokiksmaler** [comment]
They are not logging it in flash, they are logging it to RAM. This has, according to my tests, almost no influence on camera performance.

**Comment by Tommixoft** [comment]
So if camera is turned off - this log disappears yes? If no than it logs to flash.

**Comment by ottokiksmaler** [comment]
If you remove the battery the log disappears (most of it, first section is regenerated when the firmware is made or when hibernation image is rebuilt - just like in Vasile on-wake procedure). Other than that it lives in memory. 
Please do understand that the power off just puts camera to very low power sleep - to actually power of town you need to remove the battery.

**Comment by Tommixoft** [comment]
So when i turn camera off (by button) whole OS still running? RAM content is not stored to flash memory?

**Comment by ottokiksmaler** [comment]
Dude, seriously, when you power the camera down it goes to sleep (just like a laptop) but its sleep is **very** low power as the SoC was designed that way. OS is not running, some minimal set of HW is (watchdog timer, interrupt controller or similar, etc). Nothing is stored to flash. You can believe it or not, but I strongly suggest you leave it at that.

**Comment by Tommixoft** [comment]
:D i believe.. i just dont know linux. Linux is for people who had issues with easy things :D I dont. Thanks. will attach multimeter and will look at how much this sucker draws energy in sleep. :)

**Comment by ottokiksmaler** [comment]
Oh my, this has **nothing** to do with Linux... Your windows laptop does the same thing.

**Comment by ottokiksmaler** [comment]
FWIW, 
It's controlled by ```/opt/etc/dlog.conf``` and ```PlatformLogs``` directive
```
[root@drime5 ~]£ cat /dev/log_main &
...
[root@drime5 ~]£ vi /opt/etc/dlog.conf                                   
...
PlatformLogs                   on        £ Possible values are 'on' and 'off'
...
[root@drime5 ~]£ /usr/bin/st cap capdtm setusr ADJUSTSHUTTERTYPE 0x750001
v��AlZSYS_DEVICE_PLUGINdevice_manager_plugin_drime5.c: OEM_sys_muic_node_path_info(422) > uart path node not found
H��AQlMM_SESSIONMGRaudio-session-mgr.c: __ASM_init_module(2342) > <ENTER> 
H��A[nMM_SESSIONMGRaudio-session-mgr.c: __ASM_init_module(2353) > <LEAVE> 
UserData is set
G��A��MM_SOUNDmm_sound_client.c: MMSoundClientCallbackFini(97) > <ENTER> 
H��A��MM_SOUNDmm_sound_client.c: MMSoundClientCallbackFini(119) > <LEAVE> 
@��A��MM_SESSIONmm_session.c: __mmsession_finalize(924) > <ENTER> 
@��A�MM_SESSIONmm_session.c: __mmsession_finalize(944) > <LEAVE> 
H��Ar�MM_SESSIONMGRaudio-session-mgr.c: __ASM_fini_module(2360) > <ENTER> 
H��A��MM_SESSIONMGRaudio-session-mgr.c: __ASM_fini_module(2408) > <LEAVE> 

[root@drime5 ~]£ vi /opt/etc/dlog.conf                                   
...
PlatformLogs                   off        £ Possible values are 'on' and 'off'
...
[root@drime5 ~]£ /usr/bin/st cap capdtm setusr ADJUSTSHUTTERTYPE 0x750001
v�����SYS_DEVICE_PLUGINdevice_manager_plugin_drime5.c: OEM_sys_muic_node_path_info(422) > uart path node not found
UserData is set
```
But, IMHO, this affects only the newly started programs so it would have to be modified before the hibernation image is created to affect di-camera-app.

**Comment by Tommixoft** [comment]
Thanks. so when you find a way to modify this image then we could disable :) but if this is stored in ram then not very important...i was thinking it goes to flash
