### ISSUE TITLE
Suggestion: trick the DI-app to drop cpu usage

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#68]
Stupid title but cant think of how to call it.
Well my intention is to make battery last longer, this camera's battery is just nonsence, very quickly dies. SO i think of mod - by clicking lets say MOBILE button LCD goes off, BUT main battery drainer is cpu. and if lens cap is off - camera app uses twice much cpu power than with cap on. Maybe it's hunting for faces, calculates exposures..it works. 
SO i idea is -what possible best script we can run to trick camera into being "dumb". and drop it's cpu usage in half like with cap on. But it should deactivate itself automatically when shutter is pressed, like lcd off does.
You @ottokiksmaler  and @vasile-gh dig many things in camera maybe you already know something to save battery? i don't want to switch off camera frequently because of Vasile's problem with this button, i think it really may broke.

**Comment by vasile-gh** [comment]
Or you could set display off to 30 sec and power saving to something similar... :-) ?

**Comment by Tommixoft** [comment]
it never works.... dont know why are those settings in camera..i can leave camera with no pushing buttons and it never turns off.

**Comment by ottokiksmaler** [comment]
Did you turn it off in DEV menu?

**Comment by Tommixoft** [comment]
hmm what turn off in dev menu? i never was in dev menu and dont even know how to launch it. I just set 30s. in camera menu but nothing happens. Did your mod disables it? :)

**Comment by ottokiksmaler** [comment]
No, it does not.

**Comment by Tommixoft** [comment]
So this is samsung bug. cause after 30 secs lcd is still on and after 1 min camera never shuts down. BTW i was thinking im talking to vasile so that's why i refered as "your mod" so ignore it :)

**Comment by vasile-gh** [comment]
@Tommixoft please look in the DEV menu and make sure the powere savings are NOT disabled.

**Comment by Tommixoft** [comment]
cant find how to go to dev menu, waiting for your replay, i asked few minutes ago how to get into dev menu. You write that nx-patch enables it but needs key dance...which i dont know.

**Comment by vasile-gh** [comment]
google is your friend "nx500 dev menu".

**Comment by Tommixoft** [comment]
Wow with age i really getting more stupid... some time ago i was calling people idiots..now im the one... thanks.
