### ISSUE TITLE
Black screen [like lens cap on] when enabling 2.5K

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#7]
Oto, pls what im missing... got camera (nx500). whenever i do sys_param movie size 2560_1440_30p in nx_cs.adj  i have veird problem - it looks like lens cap would be ON -i see black. i see onscreen menus but cant see image. Talking about real time preview..
Also there is no greendots and touchscreen doest work.
But if i use other command in adj file-lets say telnetd -all good. WTF?

**Comment by Tommixoft** [comment]
looks like movie mode is permanent even without files on card. Thats good. strange thing is that your 2.5k bitrate is 12Mb/s mine about 1.2Mbs

Bit rate                    : 1 112 Kbps
Width                       : 2 560 pixels
Height                      : 1 440 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 25.000 fps

**Comment by ottokiksmaler** [comment]
I don't know, everything should just work. What is the firmware version? 1.11? Another way is to put switching to 2.5k mode in test.sh file as described in corresponding file here (by starting dfmsd and then feeding it commands via dfmstool). 
Also, just switching off-on does not actually restart the camera, you need to pop the battery out for a few seconds. 
Regarding bitrate, we're waiting for vasile, that will be proper 2.5k only then (he had already demonstrated 2.5k video with high bitrate).

**Comment by Tommixoft** [comment]
Vasile loves to keep his knowledge to himself :) he could share how he got higher bitrate but instead he hides it and works on other stuff. well it's he's right of course. but maybe you then could dig and make it work. Anyways thanks Otto. Sorry for many questions.

**Comment by ottokiksmaler** [comment]
Questions are no problem (if I can answer them). 

But you're very wrong on vasile - he put his code for everyone to use and it's very clear what his code does. He could have waited for a better, more polished, version, release it as proprietary hack and charge money for it. He went the opposite route and released it as GPL 3. I think you seriously underestimate the effort he had to pull to devise a way to increase the bitrate in a stable manner (I am still unable to do it outside of attached debugger - nice for testing - useless for others - and it works sometimes at best).

**Comment by Tommixoft** [comment]
I do not underestimate Vasile. It's my english problem i cant express mayself clear :)

**Comment by gitvasile** [comment]
Tommixoft, I just saw your comments in here - the one about me is in the same vein as those that got you banned on EOSHD, and your problem is not your English - you get your points across very well.

**Comment by Tommixoft** [comment]
hmm not sure i completely understand what you write. Anyways -im from eastern europe in here people are not such pussies and crybabies like in USA. Maybe sometimes im a little bit harsh but i never insult people i do not write that they are fucking idiots. They have their views, i have mine. And moderators on those websites are idiots.
Funny thing is that USA always claim -"freedome of speech" yeah that's right, you only free to speak what they want to hear :)
People can choose and not read my comments, i don't see point in banning me just because some few crybabies don't like what im writing. They should grow balls and be a men :) Words don't hurt.

**Comment by ge0rg** [comment]
@Tommixoft this is a technical information site, not a forum about your balls or political views. People in here have better things to do than to follow whom you consider idiots, so please go and find another place if you want to troll around. Stick to technical issues and facts if you want to stay around.

**Comment by Tommixoft** [comment]
See what am about-people like this Lukas. When others say something-thats ok-when i do the same is somehow bad thing. Lukas DONT READ IF YOU DONT LIKE!  This is my ISSUE -create your own if you need attention :)

**Comment by ottokiksmaler** [comment]
I asked Georg for his, IMHO, highly regarded opinion on what we are doing here as he was the one who started hacking NX cameras in the first place with NX300. He is also contributer for this repo (like a partner developer). 

So, please be polite and stick to technical issues.
