### ISSUE TITLE
siditm power drain

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#70]
http://www.dpreview.com/forums/post/57979301

**Comment by siditm** [comment]
Hi Vasile,
I've installed **only** nx-on-wake (green LED on power ON _111_111_1_1_1_) and started recording FHD@60 24 minutes clips (25 min limit present), the camera turned off after **2h 38m - Low battery** (on power on it shows one bar, so not even critical level). Test was done in with three parts, few hours of power down no USB and removed battery breaks between.

I'm starting to fear that this might be just like your double click problem on NX1, your unit is just special ;)

**Comment by vasile-gh** [comment]
@siditm how long did it last with no mod?

**Comment by siditm** [comment]
@vasile-gh  Without mod it charges up the battery to full.

**Comment by vasile-gh** [comment]
Can you install the 5.2 mod and look into the Dev menu and make sure power save features are not disabled?

**Comment by vasile-gh** [comment]
You know how to do it right? The key dance floor dev menu.

**Comment by siditm** [comment]
Mod v5.3:
DEV Mode
2. System patrameter
(4) Disable power save [ ] - unchecked

**Comment by vasile-gh** [comment]
ok do you know anything about telnet? I need you to run a command for me

**Comment by siditm** [comment]
I only get an empty file 0 bytes. Putty session below
```
*                 SAMSUNG LINUX PLATFORM                   *
************************************************************

drime5 login: root
[root@drime5 ~]# log >/sdcard/fulllog.txt
[root@drime5 ~]#
```

**Comment by vasile-gh** [comment]
did you look on your SD card? :-)

**Comment by siditm** [comment]
Yup on SD card, log works fine:
[putty session](http://pastebin.com/KnMvVZrv)

**Comment by vasile-gh** [comment]
the log is incomplete. Can you please pull the battery and then put it back in and repeat log extraction? then just take the output from the SD card.

**Comment by siditm** [comment]
Did that, it only produces an empty file.

EDIT: Apparently third time is the charm.
[fulllog.txt](https://github.com/ottokiksmaler/nx500_nx1_modding/files/337788/fulllog.txt)

**Comment by vasile-gh** [comment]
what lens did you have on when you did the mod install?

**Comment by siditm** [comment]
PZ 16-50mm with newest FW 1.30 update

**Comment by vasile-gh** [comment]
ok for the moment I cannot see anything wrong in the log. There is a SD card error message at some point but I doubt it is related and in any case you said the SD card did not cause issues on standard firmware.

I guess you followed the instructions to the letter (language, power settings, etc.) during install, right?

Can I ask you to leave the mod on and login with telnet and type this: 
`killall nx-on-wake keyscan telnetd`
This should kill everything related to the mod (including the nx-on-wake mod and telnet. You should be disconnected from telnet.

Then can you do your measurements again to see what is the power consumption and report back?

thanks

@ottokiksmaler any ideas?

**Comment by siditm** [comment]
Yup fresh install of FW 1.12 then language set to english (german is default), display off = OFF, power save = 30 min, rest done with a stopwatch, wifi & bt both off, USB port disconnected, battery at 100%, PZ 16-50mm lens connected, no flash. 
Will do the _killall_ tomorrow. The only difference I can spot is the green LED flash pattern, I get long, long, longer_break, short, short, short after turing the camera on.
BTW running on a USB power bank (1.0 A output) when in menu battery is actually charging.

**Comment by siditm** [comment]
Got disconnected but recording limit is still disabled.

**Comment by vasile-gh** [comment]
yes, that limit is not "killed" because the di-camera-app itself is patched. The flash pattern: what do you get after you pull he battery and turn on the camera? (AFTER you installed both mods) You should get two not so long blinks followed by a break and three short blinks.

**Comment by siditm** [comment]
I do get that exact pattern.
I need to get a proper current sensor to get a more accurate current readouts.
Camera really dose not want to turn on with a miltimeter (in mA range) in series even after bumping voltage to get 7.5 V going to battery compartment.

**Comment by siditm** [comment]
For now I can only say that after executing killall and starting new recording FHD@60 with USB charger connected got a Low Battery message after 20 minutes (1/3 battery before that).

**Comment by siditm** [comment]
@vasile-gh is there a command to get battery voltage?

**Comment by vasile-gh** [comment]
yes but does not work. 
_I do get that exact pattern._ => which exact pattern?

_For now I can only say that after executing killall and starting new recording FHD@60 with USB charger connected got a Low Battery message after 20 minutes_ => does this mean very high power consumption?

**Comment by siditm** [comment]
> You should get two not so long blinks followed by a break and three short blinks.
I see this pattern.

I need to order a proper shunt resistor (100mΩ; ±1%) to measure current more precisely, I'll report back.

**Comment by siditm** [comment]
I did try to measure the current consumption but due to inductive nature of the load (DC to DC cnoverter in camera body) I am unable to repeat my measuments two times in a row making them invalid (unconfirmed by repitition).
Nonetheless the fact remains my NX500 cannot charge battery while recording (mod v5.3).
I am having all sorts of glitches (tested with Samsung USB charger connected) after long recording sessios (sometimes even just after power up) e.g.
1) GUI not showing after I press record button but black bars on top and bottom and blinking green LED so the camera seems to be recording, buttons don't work I need to pull the battery

2) Camera freezes after I hit record - battery pull.

3) Camera stops recording after few seconds, repeatedly

4) Camera won't record another clip in [P] but records just fine after switching to [AUTO].

I am attempting to get the LOG but due to almost all of the above freezing the camera it's close to impossible.
Is there a telnet command that will mirror the LOG to SD file till the camera is OFF?

I'm going to order original BP-1030 as BP-1130 is not available in my area.

**Comment by vasile-gh** [comment]
ok I have another suggestion: 

1. take lens off (put the cap on, do not want dust in there)
2. re-flash v1.12
3. do a factory reset
4. set mode dial to auto
5. set language to English
6. set display power saving to 5 min
7. set power saving to 10 min
8. proceed with the rest of the nx-on-wake install as instructed in the README (except changing the power settings)

report back. Thx

**Comment by siditm** [comment]
>  3 . do a factory reset

You mean: _settings > Reset > All_ ?

**Comment by vasile-gh** [comment]
@siditm yep

**Comment by siditm** [comment]
I've did a test run, only nx-on-wake installed, switched to NTSC, FHD@60p PRO, Samsung's USB charger.
BP-1130 battery voltage at start without any load (not really a correct way to measure it but it gives a ballpark estimate) was 8.59 V = 3/3 full.
25 min clips:
1-6th battery was 3/3 so far so good,
before clip 7th, battery dropped to 2/3
after 7th 2/3 - voltage with no load! 7.57 V - this might have gone up a bit if I wait for the battery to recover.
I've noticed a significant improvement in charging efficiency also the body is cooler to the touch so this would indicate lower power consumption.
I did not change power saving times still at 5 & 10 min.

So any suggestions where to go from here? Higher output charger? Other power saving times? NX-Patch?
Also what exactly does did steps 1-12 change that lowered power consumption?

**Comment by vasile-gh** [comment]
nx-on-wake itself consumes basically 0 power. The issue is, I think, the power state of the camera while it regenerates the hibernation image. My guess is that some of the camera subsystems (focus, maybe some other) are left in a "bad" state with your camera, and this can only be from the settings of the camera.

This is why I asked you to take the lens out (=> no AF) and had you do a complete reset (to have the cam in a known state). I would think you used to flash with CAF perhaps? and without a lens cap (i.e. with image on screen?)

Anyway, I would suggest a **last** try: re-flash v1.12 and do everything as I indicated above except instead of putting the camera in Auto, put it in **M** mode. This way the exposure and most everything else will be turned off (I hope).

If this does not fix it I am stuck - I have no other ideas.

The problem is that in order to install nx-on-wake you absolutely HAVE to rebuild the hibernation and we do not know **exactly** how Samsung triggers the hibernation image rebuild. We are probably doing something not quite right and in any case we do not know what position the PASM is when Samsung triggers the rebuild, so we are a bit blind,

PS. When I wrote "no connections" I meant it: not even the power cable, the camera should be on battery.

**Comment by siditm** [comment]
During install camera was disconnected from USB, no WiFi or BT, no lens, no flash only full battery and sd card with nx-on-wake dial set to AUTO.
After I charge up battery, I'm gonna do steps 1-12 and install nx-on-wake in M mode.

**Comment by siditm** [comment]
Any suggestions on power saving settings when installing nx-on-wake in **M** mode?

**Comment by vasile-gh** [comment]
5/10 min please

**Comment by siditm** [comment]
Ok so I might be narrowing down the culprit. After flashing FW 1.12 > Reset "All" > language change to English + 5/10 min + [M] mode > no lens, no wifi, no bt, no cabels > nx-on-wake.

In my case ** Reset > All ** switches language to German and camera to ** PAL **.
After installing nx-on-wake I started testing the camera on [AUTO] FHD@**50 (PAL)** and battery seems to be holding or at least it isn't drained that fast.
I've than switched to FHD@**60 (NTSC)**. Had 1/3 bars before recording and got "Low battery" message pretty quick ~ 20 minutes. Switched to PAL but still got "Low Battery" - this might just be initial voltage drop on power consumption spike.
At this point I've turned camera off, let it charge for 10-15 min got back to 2/3.
I'm recording @50fps now will see what happens.

P.S. I'm really shocked with the cut off voltage, ~6.9 V means ther is still at least 15/20 % capacity left in that battery.

@vasile-gh should I switch to NTSC after Reset > All to improve the hiberation image before installing nx-on-wake?

**Comment by siditm** [comment]
I've installed v5.3, switched to [P] mode and to NTSC, connected a power bank (tested 5V@1A capable) and started recording as before FHD@60p PRO (unchanged bitrate). The battery was fully charged (3/3) but the thunderbolt icon was being displayed anyway. After 2 hours of recording the **thunderbolt icon changed to 3/3 battery icon** even thow my power bank still shows a current draw (it's probably a really low current adjusted by charging controller when Li-Ion battery is almost full). I've never seen 3/3 icon before with USB power connected.
@vasile-gh Does this mean my camera is fixed?
For now it sure looks to be.

**Comment by vasile-gh** [comment]
No idea if it's fixed but it looks like yes :) 
I already updated the README to mandate putting the dial on M. 

Thanks for your cooperation in finding the solution. 

I guess I'll close this now.
