### ISSUE TITLE
HDMI live output resolution setting

### ISSUE THREAD

**Issue by bortek** [ottokiksmaler/nx500_nx1_modding#72]
Exactly this issue has not been discussed before therefore I open new issue.

I want to be able to set HDMI out resolution (out of available ones or Auto) independent of the shooting resolution. For example:

Shooting resolution 1080p (or 4K or 720p) but HDMI out set to 720p.

**Comment by bortek** [comment]
Here is the error it writes in the middle of the screen

"Shooting functions are supported
only when the HDMI output is set to 1080p"

But my output has to be 720x480p.

Anyone any input on this ?

**Comment by ottokiksmaler** [comment]
Sorry, no way to test.

**Comment by bortek** [comment]
I can volunteer as a tester :)

**Comment by bortek** [comment]
No updates I am closing this case.
