### ISSUE TITLE
anyone tried the NX3300 ?    does it work>

### ISSUE THREAD

**Issue by davidbuzz** [ottokiksmaler/nx500_nx1_modding#75]
please comment here if you've got any knowledge on if the NX hacks work on the NX3300

**Comment by ottokiksmaler** [comment]
As nx3300 is much closer to nx300 than it is to nx500 or nx1 you should check with @ge0rg as he did a lot of hacking on nx300. 
Or you could try with these things and report back whether they work. I would start with initial steps with factory mode and go from there.

**Comment by kikislater** [comment]
I have a nx1100 to test, I tried yesterday but without success, I have to read more !

Samsung's OSS Release Center is down and last time I watch image of nx300 is not yet available on this server. Futhermore I look for a firmware source code for my own camera nx1100 and nothing found

It's not so clear which process we have to do to test a camera working or not ....

**Comment by ottokiksmaler** [comment]
Nothing useful in this repository will work with nx1100 and earlier models (I have nx1000, the same model essentially - they are not based on Linux and have completely different OS and firmware). Maybe access to DEV or CS menu but that's that - no mods will work (that's the reason I bought NX500 in the first place).

**Comment by kikislater** [comment]
Good to know, thanks.
I'm lookinf for nx500 at this time !
