### ISSUE TITLE
install proper build environment

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#76]
@ottokiksmaler Am a bit stuck on building a proper environment that would allow me build shared libraries that are compatible w/di-camera-app.
Any idea on how best to proceed?

**Comment by ottokiksmaler** [comment]
You mean like the ones I make (EFL GUI apps)?

**Comment by ajavamind** [comment]
I'm also having problems with building. I installed tools on Ubuntu 16.04 and built the my_prefman test code. The problem is that I get segmentation fault when I run my_perfman on the NX500.
The build command runs without errors (need -lpthread to remove compiler error)
arm-linux-gnueabi-gcc -lpthread -o my_prefman my_prefman.c --sysroot=/home/andy/NX500/NX500_opensource/NX500_packages/standard-armv7l libprefman.so -Wl,-dynamic-linker,/lib/ld-2.13.so

I also tried with gnueabihf, same problem with segmentation fault. 
Any suggestions?

**Comment by ottokiksmaler** [comment]
What happens with other compiled executables on the camera, do they work?

**Comment by ajavamind** [comment]
I tried two other executables including hello world and all have segmentation fault with PC at 0x4.  It seems to me programs are trying to execute at 0x0 and for me that implies a linking/loader issue. Somehow my build tools are not right. I also tried libraries from 12.04 and same issue. I am using Ubuntu 16.04 desktop PC, AMD 64.

**Comment by ajavamind** [comment]
I found the problem. I was using FTP to transfer to SD card in the camera and it corrupted the executable. When I loaded directly on the SD card my_prefman worked.

**Comment by ottokiksmaler** [comment]
Weird, I use ftp all the time, but glad you have found the solution :)

**Comment by ge0rg** [comment]
Switch your ftp client from ASCII to binary mode, then it should not corrupt anything any more

**Comment by ajavamind** [comment]
Unknown to me the default Filezilla FTP settings (preferences) had checked "Treat files without extension as ASCII file" under Transfers/ file type.

**Comment by HausnerR** [comment]
Hey @ottokiksmaler, I experience problems with compiling too, but little bit different.
I want to compile your EFL GUI app (button_png.c).

Steps done:
1) NX500 source code from samsung downloaded and extracted
2) arm-linux-gnueabihf-gcc installed
3) pkg-config paths to source directory defined so propably works ok

And I have problems with include paths. Looks like compiler can't find Elementary.h. Do I need to do something more to compile this app?

Compiling simple hello world works like a charm, and binary works on camera. But no efl apps :(

**Comment by ottokiksmaler** [comment]
I have also copied libs and header files from the camera root to my dev sysroot (or you can extract it from firmware with binwalk). And I also have enlightenment / efl development environment installed under Ubuntu.
