### ISSUE TITLE
Remote viewfinder with unofficial samsung lens ?

### ISSUE THREAD

**Issue by PhilZMZ** [ottokiksmaler/nx500_nx1_modding#78]
Otto, I have another request.
Using your 5.49 mod, when “no lens release” is checked,  the camera can take a picture even if there is no lens or lens is not detected. Otherwise, it is not possible. 
With Samsung camera manager, I can remote the viewfinder and take photos with the smartphone.
But If I remove the lens, or use an unofficial samsung lens (for instance a Canon lens with an adapter) or even a lens with nx mount but without electronic connection (for instance Sigma 8mm)  Remote viewfinder doesn’t lauch and the smarphone displays somthing like “No lens. Unable to start remoteviewfinder.”
And if I remove the lens once remote viewfinder has started, remote viewfinder closes.
Do you think this could be hacked, I mean Remoteviewfinder could word without official lens ?
Best regards, Phil

**Comment by ottokiksmaler** [comment]
I have had no success in that yet. I'm interested in it personally, but it seems I'll have to make a new smart camera app for that (as it stands right now).

**Comment by ottokiksmaler** [comment]
Looks like someone already did it :) 
Look at this 
https://github.com/mewlips/nx-remote-controller-mod

**Comment by ottokiksmaler** [comment]
Or better here 
https://mewlips.github.io/nx-remote-controller-mod/

**Comment by PhilZMZ** [comment]
Wow this mod https://mewlips.github.io/nx-remote-controller-mod/ is fantastic ! Works fine, even without an "official" lens, thanks Otto for the info.

But does it work only with patch 5.3 ? Not with 2.49 ? Is there any way to make both mods (5.3 and 2.49) working together on the same camera ?

**Comment by ottokiksmaler** [comment]
I don't see anything in the code that depends on Vasile mod, this could easily be adapted to NXKS.

**Comment by mewlips** [comment]
@ottokiksmaler 
Right! Technically, it is not dependent on the specific mod. (nx-patch or nx-ks).
I have a nx1 and nx500. Both are nx-wake-on patched.
What is needed is an installation script for nx-ks mod.

@PhilZMZ
Please add the issue to my github.
https://github.com/mewlips/nx-remote-controller-mod/issues

I will start working on it.

**Comment by ottokiksmaler** [comment]
I have just asked the maintainer of NXKS to see if this could be included in that mod pack.

**Comment by ottokiksmaler** [comment]
Great work @mewlips :)

**Comment by ajavamind** [comment]
Great work everyone!
I use two NX500 cameras that are twined for 3D photography. I want to be
able to trigger both cameras simultaneously over WiFi using a single
android app. Now that a web browser may be used as a remote viewfinder etc.
it seems this is feasible. I'm an android developer, so I interested to
know what code I may use as a base starting point for writing this app? It
is important that the camera mods allow the NX500 to respond nearly
instantaneously to the shutter release request. Thanks for your help.

Andy

**Comment by ottokiksmaler** [comment]
Could you define more precisely "nearly
instantaneously"?

**Comment by PhilZMZ** [comment]
@ajavamind : I think trying to remote 2 or more NX500 via Wifi will never be as good as using a wired connection. I remote 6 NX500 with a wired connection, and if I take a photo of a stopwatch, all the photos are taken in the same 1/100s (I dont have a stopwatch displaying 1/1000s...) You can buy a connecting cord (or 2 for stereo, or more...) here on ebay : http://www.ebay.fr/itm/JJC-Remote-Control-Connecting-Cord-for-SAMSUNG-NX1-NX1000-NX20-NX210-NX300-NX500-/311592892514?hash=item488c623862:g:SvgAAOSwkx5XEGRG

**Comment by mewlips** [comment]
@ajavamind 

Here is a shell script example for 'nearly instantaneously to the shutter release request.' if in manual focus mode.

```
function take_picture() {
	ip=$1
	curl http://$ip/api/v1/input/inject?keydown=Super_L
	curl http://$ip/api/v1/input/inject?keydown=Super_R
	curl http://$ip/api/v1/input/inject?keyup=Super_R
	curl http://$ip/api/v1/input/inject?keyup=Super_L
}

take_picture 192.168.0.252 &
take_picture 192.168.0.112 &
```
I have tested this script with my nx1 (192.168.0.112) and nx500 (192.168.0.252).

Mod's daemon is already able to discover each others. (by broadcasting UDP packet)
```
$ curl http://192.168.0.112/api/v1/camera/status
{"battery_charging":false,"battery_percent":-1,
"battery_level":4,"drive":"UNKNOWN","mode":"M","hevc":"off",
"cameras":[{"ip":"192.168.0.252","packet":"NX_REMOTE|0.8|NX500|1.12|"},
{"ip":"192.168.0.112","packet":"NX_REMOTE|0.8|NX1|1.41|"}]}
```

Below source code is an android example for receiving discovery packets from cameras.
https://github.com/mewlips/nx-remote-controller-mod/blob/master/NXRemoteController/app/src/main/java/com/mewlips/nxremote/DiscoveryPacketReceiver.java

**Comment by ottokiksmaler** [comment]
If you need as little delay as possible, and you already have fixed exposure and focus, the fastest way is calling 
st cap capt single start
But like in stapp.c (by sending message directly)

**Comment by ajavamind** [comment]
Nearly instantaneously for me is 1 ms. when focus is already set. The
second camera that triggers the flash (second curtain) will signal the
studio strobe to flash. So I want to insure both cameras see the flash and
capture the scene fully. With a wired connection I do not always get a
consistent flash. My guess is the shutter trigger switch bounces so each
camera shutter starts at a different instant.

Andy

**Comment by ajavamind** [comment]
Thanks for your input

Andy

**Comment by PhilZMZ** [comment]
@mewlips 
"Please add the issue to my github. https://github.com/mewlips/nx-remote-controller-mod/issues. I will start working on it."
Which issue are you talking about ? I have another idea, I post :-)

**Comment by ajavamind** [comment]
I suspect you are right about using a wired connection.

Andy

**Comment by ajavamind** [comment]
thanks for your suggestion.

Andy

**Comment by ottokiksmaler** [comment]
Why second curtain for triggering optical slave? With low enough ambient light and slow enough shutter and first curtain flash, you should have no issues. 
Regarding 1ms - I would have to test but I doubt that would be possible with these cameras.

**Comment by KinoSeed** [comment]
@mewlips I added the issue. Glad to hear it's mod-independent.

re: synchronization of more than 1 camera - would it be possible to execute a capture at a given time
(if cameras' time is synced it may just do the trick)

**Comment by ajavamind** [comment]
I think my initial thought to use the flash 2nd (rear) curtain is
incorrect.

My goal for a 3D camera rig goal is to shoot at 1/125, F11, and ISO 100, so
the camera's shutter is open 8ms. The NX500 flash sync speed is 1/160 or
6.25 ms. The studio flash strobe(s) is/are remotely triggered by a
PocketWizard remote. Depending on the type and power of the strobe output,
the flash duration will be from perhaps half ms to maybe 4 ms long. Now
whatever camera opens the shutter first, the strobe is not yet triggered,
instead wait for the other camera to signal the strobe flash. We can't
count on which camera will release its shutter first, given shutter switch
bounce and unpredictable delays in the camera software operation, but at
least we know focus is set, so that delay is ruled out.

Assuming a flash duration of 4ms, if I choose to use 1st curtain flash for
both cameras, the other camera's shutter has to open within 4ms of the
first camera, worse case. And with short duration flash units and less
power, the camera sync delay can be more than 4 ms.

If I choose the 2nd curtain for both cameras, I need less shutter sync
delay time than 4ms and are more likely to miss the full flash duration.
So I should use first curtain flash setting.

Andy

**Comment by ottokiksmaler** [comment]
If you can control the ambient light to low level (or use a ND filter and increase strobe power) got could have ss at 1/10s or similar and have no issues at all.

**Comment by KinoSeed** [comment]
Andy, keep in mind with high shutter speeds, this happens: 
https://youtu.be/CmjeCchGRQo?t=145

**Comment by PhilZMZ** [comment]
@KinoSeed Do you think there could be a noticeable difference (moire, sharpness, aliasing...) if using "silent shutter" instead of "normal shutter" for a aerial photo taken at 1/1200s or 1/2000s  with a camera under a drone not moving too fast (less than 1m/s)?

**Comment by ajavamind** [comment]
@kinoseed thanks for the video link, it much improved my understanding of
shutter speed issues!

Andy

**Comment by KinoSeed** [comment]
@PhilZMZ "moire, sharpness, aliasing..." shouldn't be affected at all, as they have to deal with sampling/interpolation/sharpening, which does not depend on the shutter.

**Comment by PhilZMZ** [comment]
@KinoSeed Thanks for the info !
