### ISSUE TITLE
Running scripts not in factory mode

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#8]
Hello Otto, sorry again the "issue". you could share to me your email :)
Look i was banned from all websites, asshole moderators and crybabies dont like me much :dancer: 

I was thinking about linux. -this is pure linux. i dont know why you think that camera app is so important.:

My idea:
Copy your created linux app into camera system.
Your app would do this - autostart like camera app (runing like deamon). And could listen to commands via telnet (telnetd should be in system too). This would be app responsible to emergency situations-because you still have access to file system. lets say camera app cant start. This emergency app (if possible) should always try turning on WIFI. and read some files/commands from SD card.

2 app - second app would be mod app. It would live in file system, it listens to some KEY COMBO, when keycombo pressed-it shows itself to user (if possible to go onto camera app).

Idea is simple- it's linux-so use linux stuff :) camera app is just an app. yes it's for firmware flash and so on-but who cares? it's just an app, if you have backup -you can always restore it - u only need access to filesystem, so job here is to have it all the time, - telnet would be best option.

sorry messy message but you get the point, and i see you done some work -did not read it but i think you did something similar.
Cheers.

**Comment by Tommixoft** [comment]
Also maybe you can recommend where i can put command to launch telnet deamon? i dont want to execute scripts in a way who requires working camera app. wi-fi can be turned on only by camera app, what if camera app doesn't load? I think linux should have something like Windows do - startup - starts applications/commands after system boots. I think having telnet always running it's essential - and need to find a way to turn-on wifi without camera app. Maybe you know how via native linux commands? Then would be possible to make app/deamon who at startup looks for wifi file in card if it's there - tries to enable wifi. Would be best if would be possible in that wifi file add SID and password to what wifi it should connect. Having this - then i think briking will be impossible if linux still boots.

**Comment by ottokiksmaler** [comment]
Here is the problem, the camera is running linux, but it's also running another OS at the same time (on a separate cpu core, it seems there are 5 of them in total) and they have to cooperate closely (by exchanging async messages). Also, please do note before doing anything to your camera that this is not a generic linux - this is heavily customized variant made for this camera and while closely related to "a linux" is it's own species.

Camera is also **not booting** at all in normal operation. It resumes from "sleep" (actually hybrid suspend-sleep) from a partition that is populated by firmware at the time of firmware installation (and data is created by Samsung in factory or wherever). 

So, by the time we can do **anything** to camera, it has already fully booted, loaded all the drivers, started di-camera-app that in turn has mounted all other partitions and loaded and configured all other devices (seriously, they do it this way - that prevents us from just replacing the app with something else) and then it resumes it's own operation. That is the earliest point we can do anything to camera.

Relevant lines from dmesg output to illustrate our problems:
```
[ 0:    0.000000] I/KERNEL       (K   0): Booting Linux on physical CPU 0
[ 0:    0.000000] I/KERNEL       (K   0): Initializing cgroup subsys cpu
[ 0:    0.000000] I/KERNEL       (K   0): Linux version 3.5.0 (hs2704.sung@SWDA7604) (gcc version 4.4.1 (Sourcery G++ Lite 2010q1-202) ) #7 PREEMPT Wed Jun 3 14:40:29 KST 2015
[ 0:    0.000000] I/KERNEL       (K   0): CPU: ARMv7 Processor [414fc091] revision 1 (ARMv7), cr=10c53c7d
[ 0:    0.000000] I/KERNEL       (K   0): CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[ 0:    0.000000] I/KERNEL       (K   0): Machine: Samsung-DRIMe5-ES
... this is original booting that we have no access to...
...skipping...
...this is where the original sleep was called (in Samsung factory)...
[ 0:   18.517834] I/KERNEL       (K 259): d5_pmu_ip_power_on_off: started[1]
[ 0:   28.733735] I/KERNEL       (K 247): PM: Syncing filesystems ... done.
[ 0:   28.751938] I/KERNEL       (K 247): Freezing user space processes ... (elapsed 0.01 seconds) done.
[ 0:   28.751944] I/KERNEL       (K 247): PM: Shrinking memory...  
[ 0:   29.023291] I/KERNEL       (K 247): ...(14649 pages freed)
[ 0:   29.393655] I/KERNEL       (K 247): ...(7088 pages freed)
...skip...
[ 0:   30.402913] I/KERNEL       (K 247): end save_processor_state
[ 0:   30.402917] I/KERNEL       (K 247): PM: Creating hibernation image:
[ 0:   30.457599] I/KERNEL       (K 247): PM: Need to copy 16624 pages
[ 1:    1.112371] I/SYS_BTLOG    (K 247): kernel_resume start!
[ 1:    1.112380] I/KERNEL       (K 247): PM: Error 1 creating hibernation image
[ 1:    1.112386] I/KERNEL       (K 247): start restore_processor_state
[ 1:    1.112389] I/KERNEL       (K 247): start __restore_processor_state
[ 1:    1.112393] I/KERNEL       (K 247): end __restore_processor_state
[ 1:    1.112395] I/KERNEL       (K 247): end restore_processor_state
[ 1:    1.112439] I/KERNEL       (K 247): DRIME5: Adaptive Support Voltage init
[ 1:    1.112459] I/KERNEL       (K 247): DRIME5: IDS : 26(ISP), 35(ARM) PROMISE : 87 RESULT : 6
[ 1:    1.112461] I/KERNEL       (K 247): DRIME5 ASV : 6 Group
... Above you can see reset of the system clock from 30s to 0s - that is the point we turn the camera on and it starts waking up from sleep - 247 is the process id of di-camera-app on NX500 - you can see it is in charge of putting the system down and is the first thing that wakes up - no way around it...
[ 1:    7.253259] I/KERNEL       (K 319): BT: Loading driver
[ 1:    8.236944] I/KERNEL       (K 319): BT: FW download over, size 653112 bytes
[ 1:    8.731587] I/KERNEL       (K 319): BT: firmware is activated(checked 10 times)
[ 1:    8.882012] I/KERNEL       (K 319): BT: Driver loaded successfully
... and this is the end of waking up procedure 8s later...
```
So, as you can see, we cannot just remove di-camera-app and put something else as it's not read from the disk at all - it's in zswap file on disk partition 9 (compressed image of memory before sleep).
Also, it is not just a camera app like in android - this is like mashing all the userspace and some of kernel components of android - from device initialization to UI - into one app that does it all.
In their defense, they did not do this so it would make my work hard - they had to do it in order for camera to boot in 1-2s and not in 15s (noone would buy such a camera). Do note that di-camera-app is also in charge of entering DEV mode, Factory mode, Firmware upgrade, etc, etc. Essentially everything of importance on camera - you **really really do not want to mess it up - you will brick your camera**. If you brick it, you need to open it, boot it with two designated pins shorted (by soldering them together or similar) and having a custom recovery.bin (IIRC) file on the SD card. As I don't have the required recovery.bin I'm stayng well clear of bricking my camera. You should to. But, the worst part is that it seems from everything I have seen in the firmware that even if you completely replace the file on the filesystem it does not even matter as it's not actually read at all at any point in normal startup.

Regarding automatic running of a bunch of services useful for development by default - every service start, like telnet and ftp, requires time and resources as well as opening your camera to unencrypted access with no password required. This is not something I'm willing to put on my camera and I'm not going to ask others to. Whoever wants it can put it in executed script file on the SD card and cutomize it fully.

But, be patient, I'm working on a simpler solution that would start scripts from SD card without entering the factory mode or turning the Wifi on (it's attached to that last initialized BT service in dmesg output).

**Comment by Tommixoft** [comment]
Wow... it's just not as flexible as i thought. i knew from your posts it hibernates, that camera app is important..but..so much....it just almost stupid. what if 1 corrupted byte on memory chip - it would break whole system. Still i think there should be way of cloning whole camera image and putting it back, maybe that recovery.bin does that. Dont think that any developer would create system where end user app is responsible for recovery process.
And i do have patience - the thing is-that i do not know linux at this level, and i want to make this camera better but because of lack of knowledge i have to bother people like you who can approve or denied what im thinking. I do understand that you already thought about all possible ways-but i know from my developer practice - sometimes you just cant see the most obvious answers -and sometimes others step in and tell you what you're missing :)

My vacation in june 28, i hope at that time there will be 2,5K @ 70Mb/s :D
Thanks otto.  Thanks for your work, for clear Git repo. and for sharing your knowledge.

**Comment by Tommixoft** [comment]
HEY... i just trying to do your hack with bluettoth but you here:  `vi bluetoothd`
modifined BIN file...it's app... do we really have to modify program???

**Comment by ottokiksmaler** [comment]
No, you create the new file named bluetoothd (sorry, my mistake, should have been mv instead of cp)

**Comment by Tommixoft** [comment]
DAMN I HATE VI SOOOOOOOOOOOOOOOOO MUCH!!!!!!!!!!!! :D

**Comment by Tommixoft** [comment]
i cant crrete file... i deleted original using vi bluetoothd then paste content then :q! and nothing..file doesnt exists... hate VI...where is nano :D

**Comment by Tommixoft** [comment]
DID it. thanks. god hate VI most stupid tool ever. nano should be default :)
