### ISSUE TITLE
IP address and telnet in V2.56

### ISSUE THREAD

**Issue by ajavamind** [ottokiksmaler/nx500_nx1_modding#80]
With v2.56 I could not find IP address when I put into telnet mode. The display shows TELNET: without an IP address. Telnet does not work. Also for remote control there is no way to find IP address, except by using MAC address to lookup the camera in my DHCP router tables. The remote control does work with my web browser.
Can we have either telnet or remote control selected?

**Comment by KinoSeed** [comment]
_I assume you use nx-ks_


In the (latest as of now) version v2.58, there is an update for the Remote Control.

camera's IP (or "Enable WiFi") will be shown on screen, and as soon as you start RC.
Tap/press the IP to dismiss that message.

To turn off nx-rc, uncheck it from the menu.

TELNET, seems to work here, as long as you have connected to WiFi it should show the IP as before (there haven't been any changes there), but if you continue to have this issue, please let us know.

for nx-ks related issues, the best place to report them is here:
https://www.facebook.com/NXKS2/

**Comment by ajavamind** [comment]
thanks KinoSeed!
I installed NXKS2 v2.59 over the the previous install, it automatically
uninstalled the previous version, very good!
The display now shows the camera IP address when the camera menu WIFI
network is turned on.
Telnet, FTP, and RC all work fine, no problems seen. FTP can read, write,
delete files on the camera.
FTP upload photo does not show it on the camera LCD until camera turned off
and on. Minor inconvenience.
I assume when I turn off WiFi and uncheck RC, these processes will all stop
running.
Excellent work, much appreciated!

I'll copy this information above as a post to facebook page too.

Andy

**Comment by KinoSeed** [comment]
Uncheck RC and it stop it completely (process terminated and removed from memory)
If you don't uncheck it, and you restart the camera, it will auto-run again.

Telnet and FTP will not be terminated automatically on WiFi-off,
they should not take much resources for you to notice, 
however if you want them off you will need the camera restarted.

**Comment by KinoSeed** [comment]
since v2.61 WiFi and FTP are auto-turned off if there is no WiFi
