### ISSUE TITLE
FTP server

### ISSUE THREAD

**Issue by ajavamind** [ottokiksmaler/nx500_nx1_modding#81]
This is a new feature request to turn on/off an FTP server through the NX-KS menu system. Thanks!

**Comment by ottokiksmaler** [comment]
FWIW, NXKS2 is developed by Kino Seed who does (AFAIK) development and bug / feature requests over at his Facebook page, not here. 
If he doesn't reply here you should hear over to his fb page.

**Comment by KinoSeed** [comment]
I'll see about adding this feature. 

However if you like me to see messages/requests for NX-KS, please post them here:
https://www.facebook.com/NXKS2/

(otherwise you may wait for some time before I get see it)

**Comment by KinoSeed** [comment]
v2.59
added: FTP server
EV+MOBILE will now turn on Telnet *and* FTP server
