### ISSUE TITLE
 nx-on-wake mod

### ISSUE THREAD

**Issue by Pascal1965** [ottokiksmaler/nx500_nx1_modding#82]
Hi otto,
I don't understand what you mean in the Readme file:
"1. Make sure the nx-on-wake mod is installed. This mod depends on nx-on-wake."
Can you explain?
Thanks
Best regards

**Comment by vasile-gh** [comment]
he means you need to install this
<https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/nx-on-wake>
first before you can install this
<https://github.com/ottokiksmaler/nx500_nx1_modding/tree/master/video-bitrate-mods/nx-patch>
.

:-)
