### ISSUE TITLE
hdmi question.

### ISSUE THREAD

**Issue by bluys** [ottokiksmaler/nx500_nx1_modding#83]
Hello! do  you think that is posiblle to enable the hdmi output video  while 4k is recording?? i can make donations for it. thanks.  and to enable  time lapse  while the hdmi output is conected?? thanks!!!

iván.

**Comment by maximoremedios** [comment]
Hi Otto. Interested as well in having hdmi output video while 4k, in my case to use an external monitor with enbedded focus peaking. Currently if an external monitor is plugged in the NX500, the camera automatically switches from 4K to full HD. If anything is connected to the hdmi port, 4K is not possible.

Thanks and congrats for your work!

**Comment by ottokiksmaler** [comment]
Not possible (from what we know), sorry.
