### ISSUE TITLE
Command-line power zoom control?

### ISSUE THREAD

**Issue by ge0rg** [ottokiksmaler/nx500_nx1_modding#86]
Hi,

I wanted to make a time-lapse recording with zoom-in during the shots... However, so far the only way I found to control the PZ was the one described in #73:

```
st app lens pzoom tele
sleep 0.05
st app lens pzoom stop
```

Is there a more precise / more elegant way to do this?

**Comment by ottokiksmaler** [comment]
No (that I know of), but with stapp you can do it more precisely as it takes less time to send the message to the lens Sve you can do it all in C without exiting to shell.
