### ISSUE TITLE
I don't understand (remember ?) how to use your mod_lapse tool

### ISSUE THREAD

**Issue by PhilZMZ** [ottokiksmaler/nx500_nx1_modding#87]
Hi Otto,
Maybe you remember, on september the 20th, you told me
![image](https://cloud.githubusercontent.com/assets/19627664/19700622/4f6ea76a-9af8-11e6-94b0-63837c38f718.png)
in this issue
https://github.com/ottokiksmaler/nx500_nx1_modding/issues/77
Your  mod_lapse tool  is [on this link](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/mod_lapse?raw=true)
A far as I remember, I tried this tool, but today I am trying to install it again and I don't understand how I did. Maybe I am really tired, I have spent 3 hours without any result.
Could you please help me (again) Otto about installing mode_lapse tool ?
I am using your 2.49 KS mod.
Best regards :-)

**Comment by KinoSeed** [comment]
Update your nx-ks, it should be already available in the time-lapse menu .

**Comment by PhilZMZ** [comment]
Works fine ! Great ! You can close the issue :-)
