### ISSUE TITLE
Focus Peaking in 4K

### ISSUE THREAD

**Issue by maximoremedios** [ottokiksmaler/nx500_nx1_modding#88]
Hi there!

Congratulations with your firmware, loving it!
Wondering if you had looked into trying to enable focus peaking in 4K on the NX500? It is available in HD but they've locked it in 4K.

Many thanks

**Comment by ottokiksmaler** [comment]
Tried it every way I could think and nothing works. I did succeed in hanging the UI on more than one occasion so it's possible that the peaking got engaged but overwhelmed the camera and froze the UI. Sorry.

**Comment by maximoremedios** [comment]
Thanks for your reply and your efforts! So annoying they've blocked it. 
Best
