### ISSUE TITLE
Is it safe to combine NX_ON_WAKE + NX-KS2?

### ISSUE THREAD

**Issue by Dave--G** [ottokiksmaler/nx500_nx1_modding#89]
Hi,

Is is possible / safe  to install both the nx_on_wake mod and the nx-ks2 mod pack at the same time?

I just installed the nx_on_wake base framework and realized the mod I need (batch record mod to work around 15-minute 4K record time limit on NX500) only exists in the KX-NS modpack.

Thanks for all the hard work you guys have put in.

**Comment by vasile-gh** [comment]
They are incompatible. However if you can live with approx 70 min (I think)
continuous recording, nx-on-wake does that without any batch recording.
Also, if you do not record the sound it can go on forever.

Rgds

**Comment by Dave--G** [comment]
Thanks for responding so quickly @vasile-gh 

Ok I see now the "all factory recording limits are disabled" are a part of nx-patch/video-bitrate-mods and will give that mod a try.

Suggest you note this incompatibility with KS-NX in the readme to avoid future confusion.

Great work.
