### ISSUE TITLE
Focus peaking with not Samsung lens

### ISSUE THREAD

**Issue by Pascal1965** [ottokiksmaler/nx500_nx1_modding#9]
Hi Otto!
Thanks for great work! Is is possible to acctivate focus peaking in "manual focus" with not Samsung lens? For instance, I have a Minolta lens with NX adaptator and I need to activate focus peaking.
Thanks a lot!
Pascal (France)

**Comment by ge0rg** [comment]
Both the focus peaking and the MF aid (zoom-in) are turned on and off with the "OK" button.

**Comment by Pascal1965** [comment]
The focus peaking doesn't work with a "non Samsung" lens. Have you done something to make it work?

**Comment by ge0rg** [comment]
I've used it just today with a "dumb" Walimex lens and a mechanical adapter. Firmware 1.11, MF aid and focus peaking enabled in the prefs. Works in all modes (P/M/A/auto/...).

**Comment by ottokiksmaler** [comment]
Georg is correct, it works.

**Comment by Pascal1965** [comment]
Do you mean "OK" button works in native on Samsung NX1 or do you mean it works with "focus_buttons" file into the script directory of the sd card?

**Comment by ottokiksmaler** [comment]
It works with normal camera without any modifications with manual lens attached. Focus buttons is used for completely different thing.

**Comment by Pascal1965** [comment]
My god! I didn't know that! I 'll try this as soon as can! Thanks a lot everybody!

**Comment by Pascal1965** [comment]
I just tryed "OK" button, This  zoom but I haven't color to help adjust focus

**Comment by ge0rg** [comment]
Either it doesn't focus properly, or you don't have Focus Peaking enabled in the Settings...

**Comment by Pascal1965** [comment]
Ok It works. You have to disable "Enlarge" in "MF Assist" and then it works :)
