### ISSUE TITLE
Android App for Manual Focus?

### ISSUE THREAD

**Issue by gnoober** [ottokiksmaler/nx500_nx1_modding#91]
Would it be possible to write an android app that shows the livestream via wifi, incl. peaking and has a slider that controls manual focus?

I'm looking to do a 0$ wireless focusing system with that for easy use on glidecams, etc. on film sets.

**Comment by ottokiksmaler** [comment]
It's possible, most likely as an addition to https://github.com/mewlips/nx-remote-controller-mod/tree/master/nx-remote-controller-daemon

Manual focus is documented already in this repo.

**Comment by gnoober** [comment]
oh yeah that app is still waiting for an android implementation :)

**Comment by mewlips** [comment]
@gnoober You can remotely control the camera from the Chrome browser on Android.
