### ISSUE TITLE
Please update to work with firmware ver 1.12 (NX500)

### ISSUE THREAD

**Issue by TabletGeek** [ottokiksmaler/nx500_nx1_modding#93]
When the NX-KS (and presumably NX-KS2) install script runs on my NX500, I receive the message "Firmware not supported". I've recently upgraded to ver. 1.12 body firmware. Would you please update this script to support ver 1.12 firmware? Thank you!

**Comment by ottokiksmaler** [comment]
Are you using nxks from this site or from official link provided in the readme file? Because version here is ancient and should not be used and nxks works fine with 1.12

**Comment by TabletGeek** [comment]
I downloaded nxks from here: https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/NX-KS.zip
This is the same location indicated in the file "NX-KS_readme.odt", which was included in the zip file that I downloaded. Is this not the correct download location?

I began modifying the scripts, where NX500 was identified by specifically searching for /bin/grep ^1.12$ /etc/version.info. However, I soon realized that several scripts use this reference and I did not want to accidentally brick my NX500 by forcing a script that might not be compatible with 1.12. If a more recent version of nxks is available, I should be using that one. Would you please provide the correct download location?

**Comment by ottokiksmaler** [comment]
Due to some friction between developers, official nxks location is as specified in this repository README file:
Use a mod with many many integrated options packed together by @KinoSeed: Read about it at facebook.com/NXKS2 or download directly from http://authors-vault.com/NX-KS2.zip - this mod is launched by enabling Bluetooth.

**Comment by vasile-gh** [comment]
AFAIK both mod flavours are now compatible with v1.12 - but the version you
downloaded is not the latest one (github version of that flavour was not
updated for a long time).

**Comment by TabletGeek** [comment]
@ottokiksmaler and @vasile-gh Thank you both for this information!
When I read the readme files for nxks and nxks2 (github versions), it appeared that nxks2 eliminated a few options from nxks in favor of providing alternate options. From my understanding of both feature sets, nxks was a better fit for me needs than nxks2. Does the newer version of nxks2 support all features of the original nxks (or is there a reason to use nxks versus nxks2)?
