### ISSUE TITLE
Long exposure not possible after mod

### ISSUE THREAD

**Issue by thelongdiv** [ottokiksmaler/nx500_nx1_modding#94]
I can usually do 1 or 0 long exposure (>=1 Second) shots with this mod enabled before it starts taking 1/1000 second shots, though I need this mod for the higher video bit rates in 4k.  In addition, sometimes it "processes" the photo for at least >5 minutes, at which point I pulled the battery.  Without the mod, 30 seconds is always sufficient.  It happens with both the NXKS mod and the Vasile-mod.

**Comment by ottokiksmaler** [comment]
Hi, I'm not able to reproduce your issue, but NXKS is tied down to Bluetooth so if you turn the Bluetooth off and then restart the camera (by removing battery to be sure) you should have your stock camera. Can you check if the problem persists in this case?

**Comment by thelongdiv** [comment]
I checked.  It literally only works if the mod is uninstalled.  I note that this is on the nx500.  I will create a video demonstrating the issue.
