### ISSUE TITLE
Focus peaking using other brand lenses with adapter

### ISSUE THREAD

**Issue by MrShadowDancer** [ottokiksmaler/nx500_nx1_modding#95]
Welcome to 2017 everyone, 

I've been wondering for a while, since I'm using an nx500 camera with a samyang 50mm canon lens + Fotodiox adapter, if it would be possible to get focus peaking to stay on after taking a picture?
Right now (if I'm correct) the way to use it is to press the "ok" button to turn it on but then once you've taken a picture it automatically turns off.
Would it be possible to keep the focus peaking turned on after taking a picture or have it turned on by half pressing the shutter button?

I'm new to Github btw, I looked to see if this was already in the mod but I couldn't really find it.
I'm grateful for any help!

**Comment by ottokiksmaler** [comment]
I have created such mod in the past, not sure if it's in NXKS2 as that's the easiest way to hack the camera. If it's not in it please reopen this issue so we can solve it. 
It worked like this - peaking and zoom are active until you half press the shutter (it then zooms out so you can frame the shot) and it reengages peaking after the shot is taken.

**Comment by MrShadowDancer** [comment]
Ahhh thank you very much!! I think I missed that. First time I'm hacking my camera but this looks promising!

**Comment by MrShadowDancer** [comment]
Don't know how to reopen this thread but I've succefully managed to "hack" my nx500 and the mod which I downloaded like you suggested has the following in the readme file:

- Auto-Peak (HalfShutter enables peaking, use OK to end peaking)

I think this is the part you were mentioning? However, I can not get this function activated by some reason. The rest of the mod is working perfect btw, there's is just no button or anything to activate this in any of the menus.

Any help is highly appreciated! :)
