### ISSUE TITLE
AE Bracket for HDR like Nikon or Canon ML

### ISSUE THREAD

**Issue by sebastian1111** [ottokiksmaler/nx500_nx1_modding#98]
I did some research and it seems Nikon cameras can do 9 exposures while Samsung and Canon only 3. Some Canon pro models can do 7.
I think NX1 can do 5. 
But Canon with Magic Lantern can do 9 as well.

Unfortunately for cinema work and 3d objects rendering and compositing - to create the so called light probes or HDR environment maps you need more than that. And even to get some difficult photos in extreme light conditions.

The light probes "are essentially snapshots of the real world that contain exquisitely detailed lighting information".
The tutorials recommends using canon and magic lantern, but I have an NX500.
Is there any way to increase to more than 3 exposures ? 
Some pics to explain better the application of this feature: 

![garage_1k](https://user-images.githubusercontent.com/32064014/30542789-6185bb12-9c89-11e7-9ef8-c20d65835eef.jpg)
![garage-768x192](https://user-images.githubusercontent.com/32064014/30542799-683b8b62-9c89-11e7-8622-923738a8f0f8.jpg)
![1](https://user-images.githubusercontent.com/32064014/30542802-6bdda0d4-9c89-11e7-9463-d4c40550687d.gif)

comparison between a good hdr image and a bad one

![hdri-dynamic-range-big](https://user-images.githubusercontent.com/32064014/30542815-719fd1ea-9c89-11e7-97bf-3f7bf2e76081.jpg)
![hdri-preview-render-close](https://user-images.githubusercontent.com/32064014/30542837-7fae782c-9c89-11e7-97f7-9e193c0eb3cc.jpg)

**Comment by ottokiksmaler** [comment]
It is possible. Have you tried NX-KS2 mod pack? IIRC it includes something like that. It's available here http://authors-vault.com/NX-KS2.zip
That said, if you shoot RAW you have ~14 stops of DR at base ISO and two additional exposures at -3 and -6 get you to 20 stops of DR in just three exposures. 
I could make an arbitrary number of exposures at arbitrary step but I would need more information on how exactly it should work (it's not possible to just add it in existing camera menus, it would have to be a part of mod).

**Comment by sebastian1111** [comment]
Thanks, I installed it and tried it.
HDR function seems similar, but it needs to be able to adjust the values.
Ramping seems it's almost there but it seems like it's made for a different purpose. 

MOD Lapse seems to be able to be set to take multiple photos, even beyond the 9 limit of magic lantern and Nikon. But I can't tell it to take pictures with different EV.
What's the "Smooth EV" option for ?

According to instructions and software available (HDRShop or Picurenaut) I need to measure and find out how many stops does the environment needs. For interiors just a few photos could be enough, for some exteriors, if using raw I need to bracket in 2 f-stop increments or 1 f-stop if using jpg.
The software expects to be given those jpg's with 1 EV increment.

And since doubling or halving of shutter speed is one stop.
So for example if I would need to take 10 photos each spaced 1 EV apart, that would mean every time the shutter speed would be increased/decreased by doubling the number.
To make it more simpler and not have a starting and ending value requirement, it would be enough to just set the starting shutter speed, and a number of photos to take.

Example:
I'll try and find the value needed for the brightest image and start with 1/10 shutter and set the photos number to 10.
The camera will immediately start to take photos, each time doubling the shutter speed.
Two seconds later we'll have the photos with:
1/10, 1/20, 1/40, 1/80, 1/160, 1/320, 1/640, 1/1280 (1/1250), 1/2560 (1/12500), 1/5120 (1/5000)
The number in parentheses are the actual shutter values, seems the camera doesn't have actual doubles over the 1/640.
There's no need to set the end shutter value since I can just delete the last 2 photos if they are too dark, over the needed values. 



 



ramping ?

**Comment by sebastian1111** [comment]
I tried again Ramping but I couldn't get it to take photos with halved shutter for each photo.

**Comment by sebastian1111** [comment]
I noticed the file 1HDR.sh has 5 segments inside, probably for each 5 photos it takes with the function HDR.
I'm guessing if I'll edit this file and make it have 9 segments instead of 5, and just run a normal install again - I could have my 9 exposures.
Probably editing this part :
"[[ $nx500 = "good" ]] &&  prefman set 0 0xa340 l 65"
For each of the 5 segments there are the values : 65, 92, 119, 146, 200
and I noticed it will take the same shutter speeds, seems they are "hard-coded"
And they are: 1/15, 1/50, 1/160, 1/500, 1/600
How do I find out what numbers do I need to get for the prefman to get other values for different shutter speeds ?

**Comment by ottokiksmaler** [comment]
It's explained here:

https://github.com/ottokiksmaler/nx500_nx1_modding/blob/18fba5e8b28c09dfd45b9fced084971b59cc6e72/doc/Working%20with%20Exposure%20Value.md

**Comment by sebastian1111** [comment]
Yes I saw that before, but it was like chinese to me :)
But I gave it another look and I found this line:

Tv = LOG(Shutter Speed)/LOG(2)*16

Which was the key. 
So in the end I was able to modify the file to allow 11 exposure. And I guess you can increase that to even more.
Then I tried to decrease the delay. The native samsung bracket takes the photos very fast.
I tried to take out the lines with the delay, or just some of the lines, and sometimes it did work, and faster, but many times would not work, or take 2 pictures with the same shutter speed and other problems.
Unfortunately even with the delay placed back sometimes it will still take 2 photos with the same shutter speed, but that's an acceptable defect. Plus it happens only rarely.

Sometimes if the shooting mode is not on single but on AE Bracket it would work together with the "HDR" mode/script. Taking 3 photos with native bracketing. But only sometimes. 
If it would work always, a faster HDR mode could be built. But I have no idea why sometimes would work and sometimes not.

**Comment by unknown2604** [comment]
I also was looking for a way to increase exposures on my NX500. Would you mind sharing your modified file? I would like to try out your configuration and do a few tests.

**Comment by sebastian1111** [comment]
Replace the file from the official install with the file from the attached zip.
And then do a normal install but with the replaced file.
But unfortunately it only works so and so.  It also takes some time with the 11 exposures from the modified file. Maybe about 40 seconds. While if I would do them manually in batches of 3 exposures - it takes only about 15 seconds.

[1HDR.zip](https://github.com/ottokiksmaler/nx500_nx1_modding/files/1423727/1HDR.zip)
