### ISSUE TITLE
Bluetooth bricked after BT-Mod installment loop

### ISSUE THREAD

**Issue by Longojing** [ottokiksmaler/nx500_nx1_modding#99]
Someone tried to install the SD card mod with Bluetooth disabled. He got the following effects:
BT-MOD detected,
Let's clean up
system is now mod clean
installing
Installation complete

This keeps looping every time. And he can not aces his Bluetooth at all anymore. Hopefully someone is still around to help me with this issue?

Image of his camera screen (NX1):
![26907026_1897864623862233_4719604619057916312_n](https://user-images.githubusercontent.com/35702757/35237410-e674249c-ffaa-11e7-888d-983496b1aaed.jpg)

Mod link that he used:
[http://authors-vault.com/NX-KS2.zip](url)

Personally i installed the mods on the NX1 and the NX500 multiple times without issues. I could not recreate his problem.

**Comment by kscm** [comment]
There have been plenty of installations with "Bluetooth disabled", so I seriously doubt that is the issue.

The mod is meant for a clean (unmodified) firmware.
Try: Take the card out, restart the camera, flash the camera with a clean firmware, and then install.

**Comment by kscm** [comment]
Or... tell him to remove the card write-protection. The card needs to be modified after the install.

**Comment by ottokiksmaler** [comment]
I cannot recreate the issue. Reflashing firmware should clear everything since there are no permanent modifications in that mod.

**Comment by ottokiksmaler** [comment]
Maybe run telnet from the SD card and see what's up with Bluetooth files that are changed by the mod.

**Comment by Longojing** [comment]
Sorry for my late reply. I will try to get him to run some of the prior examples. However. I need help with flashing the camera with a clean firmware. He didn't manage to do that so far. Though he only tried it through the original method via Samsung. And then it won't reflash. How do you force a clean reflash of the latest firmware?

**Comment by bortek** [comment]
I know this has been closed but have anyone here found a way to flash with a clean firmware ?
